import { execFileSync } from "node:child_process"
import fs from "node:fs"
import path from "node:path"
import { createRequire } from "node:module"
import { describe, expect, it } from "vitest"

const require = createRequire(import.meta.url)

/**
 * TASK-13526 Stage 1 / ADR-065: ClientPath is derived from the generated
 * @tldw/api-types path union instead of being hand-maintained. These tests pin
 * the committed artifacts' invariants (the actual type-level guarantee is
 * enforced by the extension's `tsc --noEmit -p tsconfig.compile.json`, which
 * compiles packages/ui sources against the derived union).
 */
describe("ClientPath derivation from @tldw/api-types", () => {
  const guardSource = fs.readFileSync(
    path.resolve(__dirname, "../openapi-guard.ts"),
    "utf8"
  )

  it("derives ClientPath from the generated ApiPath union", () => {
    expect(guardSource).toMatch(
      /export\s+type\s+ClientPath\s*=\s*ApiPath\b/
    )
    expect(guardSource).toMatch(/from\s+["']@tldw\/api-types["']/)
    // The hand-maintained union must not creep back in.
    const literalUnions = guardSource.match(/^\s*\|\s*"\/api\/v1\//m)
    expect(literalUnions).toBeNull()
  })

  it("ships a generated, sorted, deduplicated committed path union", () => {
    const pathsDts = fs.readFileSync(
      require.resolve("@tldw/api-types/paths"),
      "utf8"
    )
    expect(pathsDts).toContain("GENERATED by scripts/generate-api-types.mjs")

    const literals = [...pathsDts.matchAll(/^\s*\|\s*"((?:[^"\\]|\\.)*)"/gm)].map(
      (m) => m[1]
    )
    expect(literals.length).toBeGreaterThan(2000)

    const unescaped = literals.map((l) => l.replace(/\\"/g, '"').replace(/\\\\/g, "\\"))
    const sorted = [...unescaped].sort()
    expect(unescaped).toEqual(sorted)
    expect(new Set(unescaped).size).toBe(unescaped.length)

    // Known-stable contract members.
    expect(unescaped).toContain("/api/v1/health")
    expect(unescaped).toContain("/api/v1/media/add")
    // Bogus endpoints must not be present.
    expect(unescaped).not.toContain("/api/v1/definitely/not/real")
  })

  it("keeps API_PATHS satisfying the derived ClientPath (spot check)", () => {
    // API_PATHS members are `satisfies Record<string, ClientPath>`; the
    // extension compile enforces it, this guards the exported values exist
    // in the committed union so a stale regeneration can't slip through.
    const pathsDts = fs.readFileSync(
      require.resolve("@tldw/api-types/paths"),
      "utf8"
    )
    for (const known of [
      "/api/v1/media/add",
      "/api/v1/media/ingest/jobs",
      "/api/v1/media/document-upload/preflight",
      "/api/v1/media/document-upload/drafts"
    ]) {
      expect(pathsDts).toContain(`"${known}"`)
    }
  })

  it("the package generator runs end to end from the workspace", () => {
    // Smoke: the delegation entry point exists in the web shell so
    // `bun run generate:api-types` keeps working for maintainers.
    const frontendRoot = path.resolve(__dirname, "../../../../../../tldw-frontend")
    const pkg = JSON.parse(
      fs.readFileSync(path.join(frontendRoot, "package.json"), "utf8")
    )
    expect(pkg.scripts["generate:api-types"]).toBe(
      "node ../packages/api-types/scripts/generate-api-types.mjs"
    )
    const delegated = path.resolve(
      frontendRoot,
      "../packages/api-types/scripts/generate-api-types.mjs"
    )
    expect(fs.existsSync(delegated)).toBe(true)
    void execFileSync // referenced for symmetry with generation-time tooling
  })
})
