"""Constants for VN Play runtime sessions."""

from __future__ import annotations

MODE_FREEFORM = "freeform"
MODE_STORY = "story"
VN_PLAY_MODES = (MODE_FREEFORM, MODE_STORY)

SESSION_STATUS_ACTIVE = "active"
SESSION_STATUS_PAUSED = "paused"
SESSION_STATUS_COMPLETED = "completed"
SESSION_STATUS_ARCHIVED = "archived"
SESSION_STATUS_FAILED = "failed"
VN_PLAY_SESSION_STATUSES = (
    SESSION_STATUS_ACTIVE,
    SESSION_STATUS_PAUSED,
    SESSION_STATUS_COMPLETED,
    SESSION_STATUS_ARCHIVED,
    SESSION_STATUS_FAILED,
)

TRUST_LEVEL_LOCAL = "local"
TRUST_LEVEL_TRUSTED_RESTORE = "trusted_restore"
TRUST_LEVEL_UNTRUSTED_IMPORT = "untrusted_import"
TRUST_LEVEL_MIXED = "mixed"
VN_PLAY_TRUST_LEVELS = (
    TRUST_LEVEL_LOCAL,
    TRUST_LEVEL_TRUSTED_RESTORE,
    TRUST_LEVEL_UNTRUSTED_IMPORT,
    TRUST_LEVEL_MIXED,
)

LINKED_CHAT_MODE_READ_ONLY_CONTEXT = "read_only_context"
VN_PLAY_LINKED_CHAT_MODES = (LINKED_CHAT_MODE_READ_ONLY_CONTEXT,)

TURN_STATUS_PENDING = "pending"
TURN_STATUS_MODEL_CALLING = "model_calling"
TURN_STATUS_MODEL_FAILED = "model_failed"
TURN_STATUS_PARSE_FAILED = "parse_failed"
TURN_STATUS_COMPLETED = "completed"
TURN_STATUS_ABANDONED = "abandoned"
TURN_STATUS_CANCELLED = "cancelled"
VN_PLAY_TURN_STATUSES = (
    TURN_STATUS_PENDING,
    TURN_STATUS_MODEL_CALLING,
    TURN_STATUS_MODEL_FAILED,
    TURN_STATUS_PARSE_FAILED,
    TURN_STATUS_COMPLETED,
    TURN_STATUS_ABANDONED,
    TURN_STATUS_CANCELLED,
)

EVENT_SESSION_STARTED = "session_started"
EVENT_TURN_STARTED = "turn_started"
EVENT_TURN_COMPLETED = "turn_completed"
EVENT_TURN_FAILED = "turn_failed"
EVENT_USER_TURN = "user_turn"
EVENT_MODEL_TURN = "model_turn"
EVENT_CHOICE_PRESENTED = "choice_presented"
EVENT_CHOICE_SELECTED = "choice_selected"
EVENT_SCENE_STATE_CHANGED = "scene_state_changed"
EVENT_VISUAL_DIRECTIVE_REQUESTED = "visual_directive_requested"
EVENT_VISUAL_DIRECTIVE_APPLIED = "visual_directive_applied"
EVENT_VISUAL_DIRECTIVE_REJECTED = "visual_directive_rejected"
EVENT_MODEL_TURN_PARSE_FAILED = "model_turn_parse_failed"
EVENT_SAFETY_GATE_TRIGGERED = "safety_gate_triggered"
EVENT_RUNTIME_GATE_FAILED = "runtime_gate_failed"
EVENT_SESSION_SETTINGS_CHANGED = "session_settings_changed"
EVENT_SESSION_CHECKPOINT_CREATED = "session_checkpoint_created"
EVENT_SESSION_RESTORED = "session_restored"
VN_PLAY_EVENT_TYPES = (
    EVENT_SESSION_STARTED,
    EVENT_TURN_STARTED,
    EVENT_TURN_COMPLETED,
    EVENT_TURN_FAILED,
    EVENT_USER_TURN,
    EVENT_MODEL_TURN,
    EVENT_CHOICE_PRESENTED,
    EVENT_CHOICE_SELECTED,
    EVENT_SCENE_STATE_CHANGED,
    EVENT_VISUAL_DIRECTIVE_REQUESTED,
    EVENT_VISUAL_DIRECTIVE_APPLIED,
    EVENT_VISUAL_DIRECTIVE_REJECTED,
    EVENT_MODEL_TURN_PARSE_FAILED,
    EVENT_SAFETY_GATE_TRIGGERED,
    EVENT_RUNTIME_GATE_FAILED,
    EVENT_SESSION_SETTINGS_CHANGED,
    EVENT_SESSION_CHECKPOINT_CREATED,
    EVENT_SESSION_RESTORED,
)

ERROR_STALE_SCENE_VERSION = "stale_scene_version"
ERROR_TURN_IN_PROGRESS = "turn_in_progress"
ERROR_IDEMPOTENCY_KEY_CONFLICT = "idempotency_key_conflict"
ERROR_RUNTIME_GATE_FAILED = "runtime_gate_failed"
ERROR_MODEL_TURN_PARSE_FAILED = "model_turn_parse_failed"
ERROR_CHOICE_NOT_ALLOWED = "choice_not_allowed"
ERROR_INVALID_CHOICE_ID = "invalid_choice_id"
ERROR_RETRY_LAST_TURN_NOT_FAILED = "retry_last_turn_not_failed"
VN_PLAY_ERROR_CODES = (
    ERROR_STALE_SCENE_VERSION,
    ERROR_TURN_IN_PROGRESS,
    ERROR_IDEMPOTENCY_KEY_CONFLICT,
    ERROR_RUNTIME_GATE_FAILED,
    ERROR_MODEL_TURN_PARSE_FAILED,
    ERROR_CHOICE_NOT_ALLOWED,
    ERROR_INVALID_CHOICE_ID,
    ERROR_RETRY_LAST_TURN_NOT_FAILED,
)
