"""Compatibility re-exports for MCP Unified runtime interfaces."""

from mcp_unified.interfaces.runtime import (
    ApiKeyScopeNormalizer,
    AuthenticatedIdentity,
    CircuitBreakerFactory,
    DatabasePathResolver,
    EnvironmentFlagsProvider,
    LifecycleGuard,
    MCPRuntimeDependencies,
    MetricsCollector,
    ModuleConfigProvider,
    ModuleRegistry,
    NoopToolUseRecorder,
    PermissionSeeder,
    PolicyContextProvider,
    RateLimiter,
    RbacPolicy,
    RedisClientFactory,
    ServerAuthProvider,
    TelemetryProvider,
    ToolCatalogProvider,
    ToolUseRecorder,
    WebSocketCloseTarget,
    WebSocketStream,
    WebSocketStreamFactory,
)

__all__ = [
    "AuthenticatedIdentity",
    "ApiKeyScopeNormalizer",
    "CircuitBreakerFactory",
    "DatabasePathResolver",
    "EnvironmentFlagsProvider",
    "LifecycleGuard",
    "MCPRuntimeDependencies",
    "MetricsCollector",
    "ModuleConfigProvider",
    "ModuleRegistry",
    "NoopToolUseRecorder",
    "PermissionSeeder",
    "PolicyContextProvider",
    "RateLimiter",
    "RbacPolicy",
    "RedisClientFactory",
    "ServerAuthProvider",
    "TelemetryProvider",
    "ToolCatalogProvider",
    "ToolUseRecorder",
    "WebSocketCloseTarget",
    "WebSocketStream",
    "WebSocketStreamFactory",
]
