// Type-level guard keeping the frontend's API usage aligned with the
// server's OpenAPI spec. This file only exports types and helper
// functions, so it does not increase the runtime bundle size.
//
// Since ADR-065 (TASK-13526 Stage 1), ClientPath is DERIVED from the
// generated path union in @tldw/api-types (`paths.d.ts`, committed,
// regenerated by the fingerprint-gated `bun run generate` in
// apps/packages/api-types) instead of being hand-maintained. A path that
// exists in the spec type-checks; a renamed or removed backend endpoint
// becomes a compile error here rather than a runtime 404.
//
// QuickIngestModal dynamically imports the full spec when it needs it at
// runtime. MEDIA_ADD_SCHEMA_FALLBACK below is still verified against the
// spec by `bun run verify:openapi` from apps/packages/ui.

// Union of relative API paths the backend currently exposes, as generated
// from the canonical OpenAPI spec. Call sites using bgRequest/bgStream or
// direct fetch type-check against this; OpenAPI-style "{param}" segments
// are widened by ClientPathRuntime below.
import type { ApiPath } from "@tldw/api-types"

export type ClientPath = ApiPath

type ReplacePathParams<Path extends string> =
  Path extends `${infer Head}{${string}}${infer Tail}`
    ? ReplacePathParams<`${Head}${string}${Tail}`>
    : Path

// Runtime path form: replaces OpenAPI-style "{param}" segments with "${string}".
export type ClientPathRuntime = ReplacePathParams<ClientPath>

// OpenAPI paths don't include query strings, but the UI appends them at runtime.
export type ClientPathRuntimeWithQuery = ClientPathRuntime | `${ClientPathRuntime}?${string}`

// Centralized, typed API paths for use across the extension. Values are
// checked against ClientPath so that any drift from the OpenAPI spec is
// caught at compile time.
export const API_PATHS = {
  MEDIA_ADD: "/api/v1/media/add" as const,
  MEDIA_INGEST_JOBS: "/api/v1/media/ingest/jobs" as const,
  MEDIA_DOCUMENT_UPLOAD_PREFLIGHT: "/api/v1/media/document-upload/preflight" as const,
  MEDIA_DOCUMENT_UPLOAD_DRAFTS: "/api/v1/media/document-upload/drafts" as const
} as const satisfies Record<string, ClientPath>

// Allowed relative API path: anything beginning with a slash. We keep
// this wide to avoid breaking existing call sites, while ClientPath
// provides a manually-maintained list of known endpoints.
export type AllowedPath = `/${string}`

// Absolute URL permitted in a few places
export type AbsoluteURL = `${'http' | 'https'}:${string}`

export type PathOrUrl = AllowedPath | AbsoluteURL

export type ClientPathOrUrl = ClientPathRuntime | AbsoluteURL

export type ClientPathOrUrlWithQuery = ClientPathRuntimeWithQuery | AbsoluteURL

// Common HTTP methods accepted
export type AllowedHttpMethod = 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH' | 'OPTIONS' | 'HEAD'

// Any method is fine for absolute URLs; for paths, use the common set
export type AllowedMethodFor<P extends PathOrUrl> = P extends AbsoluteURL
  ? string
  : AllowedHttpMethod

// Convenience: accept lower/upper/mixed-case method annotations at call sites
export type UpperLower<M extends string> = Uppercase<M> | Lowercase<M> | M

export function normalizeMethod<M extends string>(method: M): Uppercase<M> {
  return String(method).toUpperCase() as Uppercase<M>
}
