"""Calendar domain constants."""

from __future__ import annotations

CALENDAR_DOMAIN = "calendar"
CALENDAR_SYNC_JOB_TYPE = "calendar_sync"

DEFAULT_SYNC_LOOKBACK_DAYS = 90
DEFAULT_SYNC_LOOKAHEAD_DAYS = 365
MAX_QUERY_WINDOW_DAYS = 370
MAX_EXPANDED_OCCURRENCES = 2000

CALENDAR_SOURCE_OWNER_TLDW = "tldw"
CALENDAR_SOURCE_OWNER_PROVIDER = "provider"
CALENDAR_SOURCE_OWNER_LINKED_PROJECTION = "linked_projection"

CALENDAR_ROLE_OWNER = "owner"
CALENDAR_ROLE_EDITOR = "editor"
CALENDAR_ROLE_COMMENTER = "commenter"
CALENDAR_ROLE_VIEWER = "viewer"
