"""Realtime speech protocol constants.

Keep this module dependency-free so capability and protocol tests do not import
audio provider stacks.
"""

OPENAI_REALTIME_SESSION_UPDATE = "session.update"
OPENAI_REALTIME_INPUT_AUDIO_APPEND = "input_audio_buffer.append"
OPENAI_REALTIME_INPUT_AUDIO_COMMIT = "input_audio_buffer.commit"
OPENAI_REALTIME_INPUT_AUDIO_CLEAR = "input_audio_buffer.clear"
OPENAI_REALTIME_RESPONSE_CREATE = "response.create"
OPENAI_REALTIME_RESPONSE_CANCEL = "response.cancel"

OPENAI_REALTIME_UNSUPPORTED_CONVERSATION_ITEM_CREATE = "conversation.item.create"

OPENAI_REALTIME_SESSION_CREATED = "session.created"
OPENAI_REALTIME_SESSION_UPDATED = "session.updated"
OPENAI_REALTIME_INPUT_AUDIO_COMMITTED = "input_audio_buffer.committed"
OPENAI_REALTIME_CONVERSATION_ITEM_CREATED = "conversation.item.created"
OPENAI_REALTIME_RESPONSE_CREATED = "response.created"
OPENAI_REALTIME_RESPONSE_OUTPUT_TEXT_DELTA = "response.output_text.delta"
OPENAI_REALTIME_RESPONSE_OUTPUT_AUDIO_DELTA = "response.output_audio.delta"
OPENAI_REALTIME_RESPONSE_OUTPUT_AUDIO_TRANSCRIPT_DELTA = "response.output_audio_transcript.delta"
OPENAI_REALTIME_RESPONSE_DONE = "response.done"
OPENAI_REALTIME_RATE_LIMITS_UPDATED = "rate_limits.updated"
OPENAI_REALTIME_ERROR = "error"

REALTIME_SUPPORTED_CLIENT_EVENTS = (
    OPENAI_REALTIME_SESSION_UPDATE,
    OPENAI_REALTIME_INPUT_AUDIO_APPEND,
    OPENAI_REALTIME_INPUT_AUDIO_COMMIT,
    OPENAI_REALTIME_INPUT_AUDIO_CLEAR,
    OPENAI_REALTIME_RESPONSE_CREATE,
    OPENAI_REALTIME_RESPONSE_CANCEL,
)

REALTIME_SUPPORTED_SERVER_EVENTS = (
    OPENAI_REALTIME_SESSION_CREATED,
    OPENAI_REALTIME_SESSION_UPDATED,
    OPENAI_REALTIME_INPUT_AUDIO_COMMITTED,
    OPENAI_REALTIME_CONVERSATION_ITEM_CREATED,
    OPENAI_REALTIME_RESPONSE_CREATED,
    OPENAI_REALTIME_RESPONSE_OUTPUT_TEXT_DELTA,
    OPENAI_REALTIME_RESPONSE_OUTPUT_AUDIO_DELTA,
    OPENAI_REALTIME_RESPONSE_OUTPUT_AUDIO_TRANSCRIPT_DELTA,
    OPENAI_REALTIME_RESPONSE_DONE,
    OPENAI_REALTIME_RATE_LIMITS_UPDATED,
    OPENAI_REALTIME_ERROR,
)

REALTIME_INPUT_AUDIO_FORMAT = "pcm16"
REALTIME_OUTPUT_AUDIO_FORMAT = "pcm16"
REALTIME_TLDW_TTS_REQUEST_FORMAT = "pcm"
REALTIME_WIRE_AUDIO_ENCODING = "base64_json"
REALTIME_INPUT_CHANNELS = 1
REALTIME_OUTPUT_CHANNELS = 1
REALTIME_INPUT_SAMPLE_RATE_HZ = 16000
REALTIME_OUTPUT_SAMPLE_RATE_HZ = 24000
REALTIME_INPUT_SAMPLE_WIDTH_BYTES = 2

REALTIME_MAX_JSON_FRAME_BYTES = 262144
REALTIME_MAX_BUFFERED_AUDIO_SECONDS = 30
REALTIME_MAX_BUFFERED_AUDIO_BYTES = 960000
REALTIME_MAX_OUTPUT_CHUNK_BYTES = 65536

REALTIME_AUTH_FAILURE_CLOSE_CODE = 4401
REALTIME_ENDPOINT_DENIED_CLOSE_CODE = 4403
REALTIME_QUOTA_DENIED_CLOSE_CODE = 4003
REALTIME_POLICY_VIOLATION_CLOSE_CODE = 1008
REALTIME_PAYLOAD_TOO_LARGE_CLOSE_CODE = 1009
REALTIME_INTERNAL_ERROR_CLOSE_CODE = 1011
REALTIME_NORMAL_CLOSE_CODE = 1000
