"""Public terminal cleanup keeps a discoverable registration across unlink outages."""

from __future__ import annotations

import asyncio
from types import SimpleNamespace
from typing import Any

import pytest

from tldw_Server_API.app.core.exceptions import VNAssetGenerationError
from tldw_Server_API.app.core.VN_Assets import worker as worker_module
from tldw_Server_API.app.core.VN_Assets.worker import VNAssetGenerationWorker
from tldw_Server_API.tests.VN_Assets.test_cancelled_storage_handoff import ChargedStorage
from tldw_Server_API.tests.VN_Assets.test_cancelled_storage_handoff import (
    handoff as handoff,
)
from tldw_Server_API.tests.VN_Assets.test_generation_jobs import FakeGenerationGate, FakeImageAdapter, FakeImageRegistry


@pytest.mark.integration
@pytest.mark.asyncio
@pytest.mark.parametrize("interruption", ["permission", "cancelled"])
async def test_terminal_cleanup_retries_physical_unlink_before_releasing_charge(
    handoff: SimpleNamespace, monkeypatch: pytest.MonkeyPatch, interruption: str,
) -> None:
    """Unlink failure retains owned bytes/charge and a fresh delivery finishes cleanup once."""
    storage = ChargedStorage(handoff.outputs)
    adapter = FakeImageAdapter()
    repo = handoff.service.repo
    worker = VNAssetGenerationWorker(
        repo=repo, jobs_manager=handoff.jobs, image_registry=FakeImageRegistry(adapter),
        backend_gate=FakeGenerationGate(), save_vn_asset_image=storage,
        generated_files_repo=storage, unregister_generated_file=storage.unregister,
    )
    original_attach = repo.update_item_storage

    def interrupt_attachment(*_args: Any, **_kwargs: Any) -> None:
        """Leave actual generated bytes registered but not attached to an item."""
        raise RuntimeError("interrupted storage handoff")

    monkeypatch.setattr(repo, "update_item_storage", interrupt_attachment)
    with pytest.raises(VNAssetGenerationError, match="vn_asset_storage_handoff_retryable"):
        await worker.handle_generate_variant(handoff.payload, job=handoff.job)
    monkeypatch.setattr(repo, "update_item_storage", original_attach)
    repo.cancel_batch(handoff.payload["batch_id"])
    handoff.jobs.cancel_job(handoff.job["id"])
    terminal_batch = repo.get_batch(handoff.payload["batch_id"])
    original_unlink = worker_module.unlink_vn_asset_storage_file

    def unavailable_unlink(**_kwargs: Any) -> bool:
        """Fail the physical boundary without removing real bytes."""
        if interruption == "cancelled":
            raise asyncio.CancelledError()
        raise PermissionError("temporary filesystem outage")

    monkeypatch.setattr(worker_module, "unlink_vn_asset_storage_file", unavailable_unlink)
    error = asyncio.CancelledError if interruption == "cancelled" else PermissionError
    with pytest.raises(error):
        await worker.handle_generate_variant(handoff.payload, job=handoff.job)
    assert storage.records
    assert storage.usage == len(b"fake-png")
    assert storage.removed == []
    assert list(handoff.outputs.glob("generated-*.png"))
    monkeypatch.setattr(worker_module, "unlink_vn_asset_storage_file", original_unlink)
    fresh_worker = VNAssetGenerationWorker(
        repo=repo, jobs_manager=handoff.jobs, image_registry=FakeImageRegistry(adapter),
        backend_gate=FakeGenerationGate(), save_vn_asset_image=storage,
        generated_files_repo=storage, unregister_generated_file=storage.unregister,
    )
    for _delivery in range(2):
        with pytest.raises(VNAssetGenerationError, match="vn_asset_batch_terminal"):
            await fresh_worker.handle_generate_variant(handoff.payload, job=handoff.job)
    assert storage.records == {}
    assert storage.usage == 0
    assert len(storage.removed) == 1
    assert list(handoff.outputs.glob("generated-*.png")) == []
    assert len(adapter.requests) == 1
    assert repo.get_batch(handoff.payload["batch_id"]) == terminal_batch
