"""Owned PR3071 regressions for Jobs-backed V1 retries and cancelled storage."""

from __future__ import annotations

import asyncio
from collections.abc import Generator
from pathlib import Path
from types import SimpleNamespace
from typing import Any
from uuid import uuid4

import pytest

from tldw_Server_API.app.api.v1.schemas.vn_asset_schemas import (
    VNAssetGenerationRequest,
    VNAssetPackCreate,
)
from tldw_Server_API.app.core.DB_Management.ChaChaNotes_DB import CharactersRAGDB
from tldw_Server_API.app.core.DB_Management.db_path_utils import DatabasePaths
from tldw_Server_API.app.core.exceptions import VNAssetGenerationError
from tldw_Server_API.app.core.Jobs.manager import JobManager
from tldw_Server_API.app.core.Jobs.worker_sdk import WorkerConfig, WorkerSDK
from tldw_Server_API.app.core.VN_Assets import worker as worker_module
from tldw_Server_API.app.core.VN_Assets.jobs import vn_asset_generation_jobs_queue
from tldw_Server_API.app.core.VN_Assets.service import VNAssetPackService
from tldw_Server_API.app.core.VN_Assets.worker import VNAssetGenerationWorker
from tldw_Server_API.app.services import vn_asset_jobs_worker as service_worker
from tldw_Server_API.tests.VN_Assets.test_cancelled_storage_handoff import ChargedStorage
from tldw_Server_API.tests.VN_Assets.test_generation_jobs import (
    FakeGenerationGate,
    FakeImageAdapter,
    FakeImageRegistry,
)

pytestmark = [pytest.mark.integration, pytest.mark.asyncio]


@pytest.fixture
def lifecycle(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> Generator[SimpleNamespace, None, None]:
    """Use independent temporary SQLite authorities and finite generated bytes."""
    monkeypatch.setenv("TEST_MODE", "true")
    monkeypatch.setenv("AUTO_DOWNLOAD_MODELS", "false")
    monkeypatch.setattr(DatabasePaths, "get_user_outputs_dir", staticmethod(lambda _owner: tmp_path))
    db = CharactersRAGDB(str(tmp_path / "owned-vn.db"), client_id="pr3071-vn-lifecycle")
    jobs = JobManager(db_path=tmp_path / "owned-jobs.db")
    service = VNAssetPackService(db, owner_user_id=1, jobs_manager=jobs)
    character = db.add_character_card({"name": "Finite fixture", "description": "Test only"})
    pack = service.create_pack(VNAssetPackCreate(title="Owned lifecycle", primary_character_id=character))
    slot = service.apply_matrix(pack.id, "starter", {"variant_count": 1})[0]
    storage = ChargedStorage(tmp_path)
    adapter = FakeImageAdapter()
    worker = VNAssetGenerationWorker(
        repo=service.repo,
        jobs_manager=jobs,
        image_registry=FakeImageRegistry(adapter),
        backend_gate=FakeGenerationGate(),
        save_vn_asset_image=storage,
        generated_files_repo=storage,
        unregister_generated_file=storage.unregister,
    )

    def start(variant_count: int = 1) -> int:
        """Freeze a V1 batch and fan out its real child Jobs rows."""
        batch = service.start_generation(
            pack.id,
            user_id=1,
            request=VNAssetGenerationRequest(
                slot_ids=[slot.id],
                variant_count=variant_count,
            ),
        )
        worker.handle_enqueue_batch({"user_id": 1, "pack_id": pack.id, "batch_id": batch.batch_id})
        return batch.batch_id

    yield SimpleNamespace(
        service=service,
        repo=service.repo,
        jobs=jobs,
        worker=worker,
        storage=storage,
        adapter=adapter,
        pack=pack,
        slot=slot,
        start=start,
        outputs=tmp_path,
    )
    db.close_connection()


async def deliver(
    harness: SimpleNamespace,
    *,
    backoff: int = 0,
    bind_completion_token: bool = False,
) -> dict[str, Any]:
    """Let the real SDK acquire, execute and durably settle exactly one delivery."""
    sdk = WorkerSDK(
        harness.jobs,
        WorkerConfig(
            domain="vn_assets",
            queue=vn_asset_generation_jobs_queue(),
            worker_id="pr3071-finite-worker",
            lease_seconds=120,
            retry_backoff_seconds=backoff,
            bind_completion_token=bind_completion_token,
        ),
    )
    deliveries: list[dict[str, Any]] = []

    async def handle(job: dict[str, Any]) -> dict[str, Any]:
        deliveries.append(dict(job))
        try:
            return await harness.worker.handle_job_async(job)
        finally:
            sdk.stop()

    await asyncio.wait_for(sdk.run(handler=handle, job_type="vn_asset_generate_variant"), timeout=5)
    assert len(deliveries) == 1
    return deliveries[0]


async def test_runtime_error_retries_v1_before_terminalizing(lifecycle: SimpleNamespace) -> None:
    """A transient adapter error keeps V1 active until the actual Jobs retry succeeds."""

    class OnceFailingAdapter(FakeImageAdapter):
        def generate(self, request: Any) -> Any:
            if not self.requests:
                self.requests.append(request)
                raise RuntimeError("finite transient error")
            return super().generate(request)

    adapter = OnceFailingAdapter()
    lifecycle.worker.image_registry = FakeImageRegistry(adapter)
    batch_id = lifecycle.start()
    first = await deliver(lifecycle)
    stored = lifecycle.jobs.get_job(first["id"])
    assert first["retry_count"] == 0 and first["max_retries"] == 1
    assert stored["status"] == "queued" and stored["retry_count"] == 1
    assert lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)["outcome_status"] == "planned"
    second = await deliver(lifecycle)
    assert second["id"] == first["id"] and second["retry_count"] == 1
    assert lifecycle.jobs.get_job(second["id"])["status"] == "completed"
    assert lifecycle.repo.get_batch(batch_id)["status"] == "completed"
    assert len(adapter.requests) == 2


@pytest.mark.parametrize("retryable", [True, False])
async def test_explicit_adapter_error_respects_retry_disposition(
    lifecycle: SimpleNamespace,
    retryable: bool,
) -> None:
    """Terminal VN state follows the same explicit error disposition and budget as Jobs."""

    class FailingAdapter(FakeImageAdapter):
        def generate(self, request: Any) -> Any:
            self.requests.append(request)
            raise VNAssetGenerationError("finite adapter error", retryable=retryable)

    adapter = FailingAdapter()
    lifecycle.worker.image_registry = FakeImageRegistry(adapter)
    batch_id = lifecycle.start()
    first = await deliver(lifecycle)
    if retryable:
        assert lifecycle.jobs.get_job(first["id"])["status"] == "queued"
        assert lifecycle.repo.get_batch(batch_id)["status"] != "failed"
        await deliver(lifecycle)
    assert lifecycle.jobs.get_job(first["id"])["status"] == "failed"
    assert lifecycle.repo.get_batch(batch_id)["status"] == "failed"
    assert lifecycle.repo.get_slot(lifecycle.slot.id)["status"] == "failed"
    assert len(adapter.requests) == (2 if retryable else 1)


@pytest.mark.parametrize("boundary", ["attachment", "publication"])
async def test_exhausted_storage_reconciliation_fails_without_deleting_recoverable_bytes(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
    boundary: str,
) -> None:
    """An exhausted handoff is a retryable failed batch, not a permanently active claim."""

    def unavailable(*_args: Any, **_kwargs: Any) -> None:
        raise RuntimeError("finite settlement outage")

    monkeypatch.setattr(
        lifecycle.repo, "update_item_storage" if boundary == "attachment" else "complete_variant", unavailable
    )
    batch_id = lifecycle.start()
    first = await deliver(lifecycle)
    assert lifecycle.jobs.get_job(first["id"])["status"] == "queued"
    assert lifecycle.repo.get_batch(batch_id)["status"] != "failed"
    records = dict(lifecycle.storage.records)
    second = await deliver(lifecycle)
    assert second["id"] == first["id"] and second["retry_count"] == 1
    assert lifecycle.jobs.get_job(first["id"])["status"] == "failed"
    assert lifecycle.repo.get_batch(batch_id)["status"] == "failed"
    assert lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)["outcome_status"] == "failed"
    assert lifecycle.storage.records == records
    assert lifecycle.storage.usage == len(b"fake-png")
    assert [path.read_bytes() for path in lifecycle.outputs.glob("generated-*.png")] == [b"fake-png"]
    assert len(lifecycle.adapter.requests) == 1
    assert lifecycle.service.retry_slot(lifecycle.pack.id, lifecycle.slot.id).source_batch_id == batch_id


async def test_service_queued_retry_does_not_run_terminal_callback(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The production callback wiring leaves an ordinary queued retry active."""
    monkeypatch.setenv("JOBS_QUARANTINE_THRESHOLD", "2")

    class FailingAdapter(FakeImageAdapter):
        def generate(self, request: Any) -> Any:
            self.requests.append(request)
            raise RuntimeError("finite queued retry")

    async def unexpected_callback(*_args: Any, **_kwargs: Any) -> None:
        pytest.fail("queued work must not invoke the terminal callback")

    lifecycle.worker.image_registry = FakeImageRegistry(FailingAdapter())
    monkeypatch.setattr(service_worker, "handle_vn_asset_failed_job", unexpected_callback)
    batch_id = lifecycle.start()
    acquired = await deliver_service(lifecycle, monkeypatch)
    stored = lifecycle.jobs.get_job(acquired["id"])
    assert stored["status"] == "queued" and stored["completion_token"] is None
    assert lifecycle.repo.get_batch(batch_id)["status"] == "enqueued"
    outcome = lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)
    assert outcome["outcome_status"] == "planned" and outcome["claim_lease_id"] == acquired["lease_id"]


async def quarantined_claim(
    harness: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
) -> tuple[int, dict[str, Any]]:
    """Retain a real terminal Jobs row before invoking its VN callback."""
    monkeypatch.setenv("JOBS_QUARANTINE_THRESHOLD", "1")

    class FailingAdapter(FakeImageAdapter):
        def generate(self, request: Any) -> Any:
            self.requests.append(request)
            raise RuntimeError("finite terminal disposition")

    harness.worker.image_registry = FakeImageRegistry(FailingAdapter())
    batch_id = harness.start()
    acquired = await deliver(harness, bind_completion_token=True)
    stored = harness.jobs.get_job(acquired["id"])
    assert stored["status"] == "quarantined" and stored["completion_token"] == acquired["lease_id"]
    assert harness.repo.get_variant_outcome(batch_id, harness.slot.id, 0)["outcome_status"] == "planned"
    return batch_id, acquired


@pytest.mark.parametrize(
    ("field", "replacement"),
    [
        ("uuid", "foreign-uuid"),
        ("owner_user_id", "2"),
        ("domain", "foreign-domain"),
        ("queue", "foreign-queue"),
        ("job_type", "foreign-type"),
        ("batch_group", "foreign-batch"),
        ("idempotency_key", "foreign-key"),
        ("completion_token", "other-delivery"),
        ("id", -1),
        ("payload", {"user_id": 2}),
        ("status", "queued"),
        ("status", "processing"),
        ("status", "completed"),
        ("status", "cancelled"),
    ],
)
async def test_terminal_callback_rejects_changed_jobs_authority(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
    field: str,
    replacement: Any,
) -> None:
    """A terminal Jobs read is not authority unless every delivery fence still matches."""
    batch_id, acquired = await quarantined_claim(lifecycle, monkeypatch)
    original_read = lifecycle.jobs.get_job_or_archived_by_uuid
    before_batch = lifecycle.repo.get_batch(batch_id)
    before_outcome = lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)

    def changed_read(*args: Any, **kwargs: Any) -> dict[str, Any]:
        stored = dict(original_read(*args, **kwargs))
        stored[field] = replacement
        return stored

    monkeypatch.setattr(lifecycle.jobs, "get_job_or_archived_by_uuid", changed_read)
    await lifecycle.worker.handle_failed_job(acquired, RuntimeError("delayed callback"))
    assert lifecycle.repo.get_batch(batch_id) == before_batch
    assert lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0) == before_outcome


async def test_terminal_callback_rechecks_claim_under_write_admission(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Cancellation between callback preparation and VN admission cannot be overwritten."""
    batch_id, acquired = await quarantined_claim(lifecycle, monkeypatch)
    original_fail = lifecycle.repo.fail_variant

    def cancel_before_admission(**kwargs: Any) -> None:
        lifecycle.repo.cancel_batch(batch_id)
        original_fail(**kwargs)

    monkeypatch.setattr(lifecycle.repo, "fail_variant", cancel_before_admission)
    with pytest.raises(VNAssetGenerationError, match="vn_asset_job_lease_lost"):
        await lifecycle.worker.handle_failed_job(acquired, RuntimeError("delayed callback"))
    current = lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)
    assert current["outcome_status"] == "cancelled"
    assert lifecycle.repo.get_batch(batch_id)["status"] == "cancelled"


async def test_terminal_callback_rejects_a_newer_claim(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """A real later Jobs acquisition and V1 takeover retire the old callback authority."""
    monkeypatch.setenv("JOBS_QUARANTINE_THRESHOLD", "2")

    class FailingAdapter(FakeImageAdapter):
        def generate(self, request: Any) -> Any:
            self.requests.append(request)
            raise RuntimeError("finite retry before takeover")

    lifecycle.worker.image_registry = FakeImageRegistry(FailingAdapter())
    batch_id = lifecycle.start()
    first = await deliver(lifecycle, bind_completion_token=True)
    second = lifecycle.jobs.acquire_next_job(
        domain="vn_assets",
        queue=vn_asset_generation_jobs_queue(),
        worker_id="new-owner",
        lease_seconds=120,
        job_type="vn_asset_generate_variant",
    )
    assert second["id"] == first["id"] and second["lease_id"] != first["lease_id"]
    old_outcome = lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)
    lifecycle.repo.claim_variant(
        batch_id=batch_id,
        slot_id=lifecycle.slot.id,
        variant_index=0,
        lease_id=second["lease_id"],
        attempt_token=uuid4().hex,
        item_fields={},
        allow_takeover=True,
        expected_claim_token=old_outcome["claim_token"],
        validate_authority=lambda: lifecycle.worker._require_current_job_lease(second, user_id=1),
    )
    before = lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)
    await lifecycle.worker.handle_failed_job(first, RuntimeError("old callback"))
    assert lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0) == before
    assert lifecycle.repo.get_batch(batch_id)["status"] == "enqueued"


async def test_terminal_callback_rejects_foreign_payload_owner_before_opening_database(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """The service callback keeps its existing owner-to-payload database boundary."""
    batch_id, acquired = await quarantined_claim(lifecycle, monkeypatch)
    acquired["owner_user_id"] = "2"

    async def unexpected_database(*_args: Any, **_kwargs: Any) -> None:
        pytest.fail("foreign-owner callback must not open a database")

    monkeypatch.setattr(service_worker, "get_chacha_db_for_user_id", unexpected_database)
    with pytest.raises(ValueError, match="vn_asset_job_owner_mismatch"):
        await service_worker.handle_vn_asset_failed_job(
            acquired, RuntimeError("foreign callback"), job_manager=lifecycle.jobs
        )
    assert lifecycle.repo.get_batch(batch_id)["status"] == "enqueued"


@pytest.mark.parametrize("unlink_outage", [False, True])
async def test_cancelled_sibling_storage_is_cleaned_before_queued_delivery_is_cancelled(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
    unlink_outage: bool,
) -> None:
    """A different child cannot cancel the sole retry path for a charged hidden reservation."""
    original_attach = lifecycle.repo.update_item_storage

    def unavailable(*_args: Any, **_kwargs: Any) -> None:
        raise RuntimeError("finite attachment outage")

    monkeypatch.setattr(lifecycle.repo, "update_item_storage", unavailable)
    batch_id = lifecycle.start(variant_count=2)
    first = await deliver(lifecycle, backoff=60)
    assert lifecycle.jobs.get_job(first["id"])["status"] == "queued"
    assert lifecycle.storage.usage == len(b"fake-png")
    monkeypatch.setattr(lifecycle.repo, "update_item_storage", original_attach)
    lifecycle.repo.cancel_batch(batch_id)
    terminal_batch = lifecycle.repo.get_batch(batch_id)
    original_unlink = worker_module.unlink_vn_asset_storage_file
    if unlink_outage:

        def unavailable_unlink(**_kwargs: Any) -> bool:
            raise PermissionError("finite unlink outage")

        monkeypatch.setattr(worker_module, "unlink_vn_asset_storage_file", unavailable_unlink)
    sibling = await deliver(lifecycle)
    assert sibling["id"] != first["id"]
    if unlink_outage:
        assert lifecycle.jobs.get_job(first["id"])["status"] == "queued"
        assert lifecycle.jobs.get_job(sibling["id"])["status"] == "queued"
        assert lifecycle.storage.usage == len(b"fake-png")
        monkeypatch.setattr(worker_module, "unlink_vn_asset_storage_file", original_unlink)
        assert (await deliver(lifecycle))["id"] == sibling["id"]
    assert lifecycle.jobs.get_job(first["id"])["status"] == "cancelled"
    assert lifecycle.storage.records == {}
    assert lifecycle.storage.usage == 0
    assert len(lifecycle.storage.removed) == 1
    assert list(lifecycle.outputs.glob("generated-*.png")) == []
    assert len(lifecycle.adapter.requests) == 1
    assert lifecycle.repo.get_batch(batch_id) == terminal_batch
    assert (
        lifecycle.jobs.acquire_next_job(
            domain="vn_assets",
            queue=vn_asset_generation_jobs_queue(),
            worker_id="no-redelivery",
            lease_seconds=120,
            job_type="vn_asset_generate_variant",
        )
        is None
    )


async def deliver_service(
    harness: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
) -> dict[str, Any]:
    """Run the real production SDK wiring with a finite injected generation handler."""
    deliveries: list[dict[str, Any]] = []
    sdks: list[WorkerSDK] = []

    def sdk_factory(manager: JobManager, config: WorkerConfig) -> WorkerSDK:
        sdk = WorkerSDK(manager, config)
        sdks.append(sdk)
        return sdk

    async def handle(job: dict[str, Any], **_kwargs: Any) -> dict[str, Any]:
        deliveries.append(dict(job))
        try:
            return await harness.worker.handle_job_async(job)
        finally:
            sdks[0].stop()

    async def own_db(owner: int, **_kwargs: Any) -> CharactersRAGDB:
        assert owner == 1
        return harness.repo.db

    monkeypatch.setattr(service_worker, "JobManager", lambda: harness.jobs)
    monkeypatch.setattr(service_worker, "WorkerSDK", sdk_factory)
    monkeypatch.setattr(service_worker, "handle_vn_asset_job", handle)
    monkeypatch.setattr(service_worker, "get_chacha_db_for_user_id", own_db)
    await asyncio.wait_for(service_worker.run_vn_asset_generation_jobs_worker(), timeout=5)
    assert len(deliveries) == 1
    return deliveries[0]


@pytest.mark.parametrize("boundary", ["runtime", "explicit", "attachment", "publication"])
async def test_first_delivery_quarantine_terminalizes_exact_v1_claim(
    lifecycle: SimpleNamespace,
    monkeypatch: pytest.MonkeyPatch,
    boundary: str,
) -> None:
    """Verified Jobs quarantine must settle V1 even before its retry budget is spent."""
    monkeypatch.setenv("JOBS_QUARANTINE_THRESHOLD", "1")

    class FailingAdapter(FakeImageAdapter):
        def generate(self, request: Any) -> Any:
            self.requests.append(request)
            if boundary == "explicit":
                raise VNAssetGenerationError("finite quarantine error", retryable=True)
            raise RuntimeError("finite quarantine error")

    def unavailable(*_args: Any, **_kwargs: Any) -> None:
        raise RuntimeError("finite quarantine handoff outage")

    if boundary in {"runtime", "explicit"}:
        lifecycle.worker.image_registry = FakeImageRegistry(FailingAdapter())
    else:
        monkeypatch.setattr(
            lifecycle.repo,
            "update_item_storage" if boundary == "attachment" else "complete_variant",
            unavailable,
        )
    batch_id = lifecycle.start()
    acquired = await deliver_service(lifecycle, monkeypatch)
    stored = lifecycle.jobs.get_job(acquired["id"])
    assert acquired["retry_count"] == 0 and acquired["max_retries"] == 1
    assert stored["status"] == "quarantined"
    assert stored["retry_count"] == 1 and stored["lease_id"] is None
    assert lifecycle.repo.get_batch(batch_id)["status"] == "failed"
    assert lifecycle.repo.get_variant_outcome(batch_id, lifecycle.slot.id, 0)["outcome_status"] == "failed"
    assert lifecycle.repo.get_slot(lifecycle.slot.id)["status"] == "failed"
    if boundary in {"attachment", "publication"}:
        assert lifecycle.storage.usage == len(b"fake-png")
        assert len(lifecycle.storage.records) == 1
        assert [p.read_bytes() for p in lifecycle.outputs.glob("generated-*.png")] == [b"fake-png"]
    else:
        assert lifecycle.storage.records == {}
    assert lifecycle.service.retry_slot(lifecycle.pack.id, lifecycle.slot.id).source_batch_id == batch_id
