#!/usr/bin/env python3
"""Explicit, test-only real VZ fault preparation and acceptance workflow."""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import platform
import shutil
import signal

# Operator-selected local build/test tools; commands never use a shell.
import subprocess  # nosec B404
import sys
import tempfile
import traceback
from contextlib import contextmanager
from dataclasses import asdict
from pathlib import Path
from typing import Any

# Reports are generated by pytest in the private run, never downloaded.
from xml.etree import ElementTree as ET  # nosec B405

REPO = Path(__file__).resolve().parents[3]
FIXTURES = REPO / "tools/macos-vz-helper/Tests/failure_drill"
TESTS = {
    "mismatch": (
        "test_vz_linux_guest_mismatch_host_gated.py",
        "test_vz_linux_rejects_real_guest_missing_exec_then_runs_healthy_session",
        "Mismatched guest was not rejected",
        "TLDW_SANDBOX_VZ_LINUX_MISMATCH_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_GUEST_MISMATCH_DRILL",
    ),
    "readiness": (
        "test_vz_linux_readiness_host_gated.py",
        "test_vz_linux_readiness_timeout_then_healthy_session_reuse",
        "Readiness withholding did not fail",
        "TLDW_SANDBOX_VZ_LINUX_READINESS_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_READINESS_DRILL",
    ),
}


def load_module(name: str, path: Path) -> Any:
    """Reuse repository scripts without duplicating their safety contracts."""
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def digest(path: Path) -> str:
    """Hash artifacts without loading disk images into memory."""
    with path.open("rb") as handle:
        return hashlib.file_digest(handle, "sha256").hexdigest()


def write_json(path: Path, value: Any) -> None:
    """Keep readable receipts inside the exclusively owned evidence directory."""
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


def create_evidence(path: Path, source: Path) -> Path:
    """Refuse reuse and source containment, including through directory aliases."""
    path = path.expanduser().absolute()
    if path.resolve().is_relative_to(source.resolve()):
        raise ValueError("evidence must not be inside the source bundle")
    path.mkdir(mode=0o700)  # Parent must already exist; never overwrite an old run.
    return path.resolve()


def replace_once(source: str, anchor: str, replacement: str) -> str:
    """Fail closed if a production refactor invalidated a test-only overlay."""
    if source.count(anchor) != 1:
        raise ValueError("guest overlay anchor missing or ambiguous; review source drift")
    return source.replace(anchor, replacement, 1)


def test_result(path: Path, code: int, profile: str, negative: bool) -> dict[str, Any]:
    """Require one exact test and distinguish intended RED from unrelated failure."""
    result: dict[str, Any] = {"ok": False, "exit_code": code}
    try:
        tree = ET.parse(path)  # nosec B314
    except (OSError, ET.ParseError) as exc:
        return {**result, "error": str(exc)}
    cases = list(tree.iter("testcase"))
    counts = {key: len(list(tree.iter(key))) for key in ("failure", "error", "skipped")}
    result.update(tests=len(cases), **counts)
    failures = list(tree.iter("failure"))
    if len(cases) != 1 or cases[0].get("name") != TESTS[profile][1]:
        return result
    result["ok"] = (
        code == int(negative)
        and counts == {"failure": int(negative), "error": 0, "skipped": 0}
        and (not negative or failures[0].get("message", "").startswith("Failed: " + TESTS[profile][2] + ":"))
    )
    return result


def cleanup_vms(helper: Any) -> dict[str, Any]:
    """Clean every VM on this workflow's exclusive helper, retaining all errors."""
    errors = []
    remaining = None
    try:
        vms = helper.list_vms().vms
    except Exception as exc:  # noqa: BLE001 - accumulate failures; never abandon later cleanup
        errors.append(f"enumerate: {exc}")
    else:
        for vm in vms:
            try:
                if not helper.terminate_vm(vm.vm_id):
                    errors.append(f"terminate {vm.vm_id}: not confirmed")
            except Exception as exc:  # noqa: BLE001 - every cleanup error makes acceptance fail
                errors.append(f"terminate {vm.vm_id}: {exc}")
    try:
        remaining = [vm.vm_id for vm in helper.list_vms().vms]
    except Exception as exc:  # noqa: BLE001 - unavailable verification is a failed result
        errors.append(f"verify enumeration: {exc}")
    return {"ok": not errors and remaining == [], "errors": errors, "remaining_vm_ids": remaining}


def negative_execution(packet: Path, profile: str) -> dict[str, Any]:
    """A negative control must prove completed execution in the actual fault VM."""
    filename = "guest-mismatch.json" if profile == "mismatch" else "guest-readiness.json"
    paths = [p for p in (packet / "pytest").glob("*/" + filename) if not p.parent.is_symlink() and not p.is_symlink()]
    if len(paths) != 1:
        return {"ok": False, "error": "expected exactly one guest receipt"}
    try:
        data = json.loads(paths[0].read_text(encoding="utf-8"))
        runs, created = data["runs"], data["created_vms"]
        if len(runs) != 1 or len(created) != 1:
            raise ValueError("expected one fault run and one fault VM")
        run, vm_id = runs[0], created[0]["vm_id"]
        ok = (
            isinstance(vm_id, str)
            and bool(vm_id)
            and run["phase"] == "completed"
            and run["exit_code"] == 0
            and run["stdout"] == profile + "-drill-first\n"
            and data["exec_vm_ids"] == [vm_id]
            and data["cleanup_errors"] == []
            and data["remaining_owned_vms"] == []
        )
        if profile == "readiness":
            proof = data["handshake_proof"]
            ok = ok and proof["vm_id"] == vm_id and proof["handshake_acknowledged"] is True
        return {"ok": ok, "receipt": str(paths[0]), "vm_id": vm_id, "run": run}
    except (OSError, ValueError, TypeError, KeyError) as exc:
        return {"ok": False, "error": str(exc)}


def disk_handles(disks: list[Path]) -> dict[str, Any]:
    """Require positive evidence of closed disks, not merely an empty registry."""
    if not disks:
        return {"ok": True, "reason": "no disks allocated"}
    result = subprocess.run(  # nosec B603
        ["/usr/sbin/lsof", "-Fpcn", "--", *map(str, disks)],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    return {
        "ok": result.returncode == 1 and not result.stdout and not result.stderr,
        "exit_code": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


@contextmanager
def managed_helper(ctl: Any, binary: Path, evidence: Path, receipt: dict, disks: list[Path], client_factory: Any):
    """Own a fresh short socket path; never attach to or stop another helper."""
    # mkdtemp creates an exclusive 0700 directory; /tmp keeps AF_UNIX paths short.
    runtime_name = tempfile.mkdtemp(prefix="tvz-fault.", dir="/tmp")  # nosec B108
    runtime = Path(runtime_name).resolve()
    socket_path, pid_file = runtime / "helper.sock", runtime / "helper.pid"
    lifecycle = receipt["lifecycle"] = {"runtime_dir": str(runtime), "socket_path": str(socket_path)}
    helper = None
    start_attempted = False
    try:
        preflight = ctl.collect_check_results(binary, socket_path, pid_file, evidence / "helper-logs")
        lifecycle["preflight"] = {name: asdict(result) for name, result in preflight}
        if not all(result.ok for _, result in preflight):
            raise RuntimeError("helper preflight failed; see lifecycle receipt")
        start_attempted = True
        lifecycle["start"] = asdict(ctl.start_helper(binary, socket_path, pid_file, evidence / "helper-logs"))
        if not lifecycle["start"]["ok"]:
            raise RuntimeError("managed helper start failed")
        helper = client_factory(socket_path)
        yield helper, socket_path
    finally:
        # Independently attempt cleanup, disk verification, stop, and absence proof.
        actions = []
        if helper is not None:
            actions.append(("vms", lambda: cleanup_vms(helper)))
        actions.append(("disk_handles_before_stop", lambda: disk_handles(disks)))
        if start_attempted:
            actions.append(("stop", lambda: asdict(ctl.stop_helper(binary, pid_file, socket_path=socket_path))))
        for name, action in actions:
            try:
                lifecycle[name] = action()
            except Exception as exc:  # noqa: BLE001 - persist each failure and still stop the helper
                lifecycle[name] = {"ok": False, "error": str(exc)}
            if not lifecycle[name]["ok"]:
                receipt["errors"].append(f"helper cleanup: {name}")
        try:
            absent = not ctl.socket_accepts_connection(socket_path) and not pid_file.exists()
            lifecycle["absent"] = absent
            if not absent:
                raise RuntimeError("helper absence not confirmed; retain runtime directory")
            runtime.rmdir()
            lifecycle["runtime_removed"] = True
        except Exception as exc:  # noqa: BLE001 - retain evidence and fail closed
            lifecycle["runtime_removed"] = False
            receipt["errors"].append(f"runtime cleanup: {exc}")


def logged(
    command: list[str], log: Path, *, cwd: Path = REPO, env: dict[str, str] | None = None, timeout: int = 180
) -> int:
    """Run a bounded local command and retain output even when it fails."""
    with log.open("w", encoding="utf-8") as handle:
        result = subprocess.run(  # nosec B603
            command,
            cwd=cwd,
            env=env,
            stdout=handle,
            stderr=subprocess.STDOUT,
            timeout=timeout,
            check=False,
        )
    return result.returncode


def build_agent(profile: str, packet: Path) -> Path:
    """Build a Linux arm64 test guest without modifying the production checkout."""
    original = REPO / "tools/tldw-agent/internal/guest/vsock_client.go"
    source = original.read_text(encoding="utf-8")
    if profile == "mismatch":
        source = replace_once(source, 'return []string{"exec", "output_cap_v1"}', 'return []string{"output_cap_v1"}')
    else:
        anchor = "\tif err := c.sendReady(conn, reader, server); err != nil {"
        source = replace_once(source, anchor, (FIXTURES / "withhold-ready.go.txt").read_text() + anchor)
    overlay_source = packet / "vsock_client.go"
    overlay_source.write_text(source, encoding="utf-8")
    overlay = packet / "overlay.json"
    write_json(overlay, {"Replace": {str(original): str(overlay_source)}})
    binary = packet / "tldw-agent-guest"
    env = {
        **os.environ,
        "GOOS": "linux",
        "GOARCH": "arm64",
        "CGO_ENABLED": "0",
        "GOPROXY": "off",
        "GOSUMDB": "off",
        "GOTOOLCHAIN": "local",
    }
    command = ["go", "build", "-overlay=" + str(overlay), "-o", str(binary), "./cmd/tldw-agent-guest"]
    if logged(command, packet / "build.log", cwd=REPO / "tools/tldw-agent", env=env) != 0:
        raise RuntimeError(f"{profile} guest build failed; see {packet / 'build.log'}")
    write_json(
        packet / "build.json",
        {
            "profile": profile,
            "command": command,
            "production_source_sha256": digest(original),
            "overlay_sha256": digest(overlay_source),
            "agent_sha256": digest(binary),
        },
    )
    return binary


def fingerprint(materializer: Any, bundle: Path) -> dict[str, str]:
    """Hash boot artifacts and metadata, including optional build provenance."""
    names = materializer.bundle_artifact_names(bundle)
    names += [name for name in ("manifest.json", "build-info.json") if (bundle / name).is_file()]
    return {name: digest(bundle / name) for name in names}


def verify_sources(materializer: Any, source: Path, evidence: Path, receipt: dict[str, Any]) -> None:
    """Independently verify canonical and prepared sources, even after failed drills."""
    sources = [("canonical", source, receipt.get("source_before"))]
    sources.extend(
        (profile, evidence / "image-store/runs" / (profile + "-source/bundle"), hashes)
        for profile, hashes in receipt.get("fault_sources", {}).items()
    )
    for label, bundle, before in sources:
        unchanged = False
        try:
            after = fingerprint(materializer, bundle)
            unchanged = after == before
            if label == "canonical":
                receipt["source_after"] = after
            if not unchanged:
                raise RuntimeError("source changed")
        except Exception as exc:  # noqa: BLE001 - independently verify every source on failure
            receipt["errors"].append(f"{label} source verification: {exc}")
        if label != "canonical":
            receipt.setdefault("fault_sources_unchanged", {})[label] = unchanged


def clone(materializer: Any, source: Path, evidence: Path, run_id: str, template: str, disks: list[Path]) -> Path:
    """Use the same image-store clone abstraction as the normal smoke wrapper."""
    bundle = materializer.prepare_bundle(
        materializer.parse_args(
            [
                "--source-bundle",
                str(source),
                "--store-root",
                str(evidence / "image-store"),
                "--run-id",
                run_id,
                "--template-name",
                template,
            ]
        )
    )
    disks.append(bundle / "rootfs.img")
    return bundle


def install_agent(helper: Any, boot: Path, target: Path, binary: Path, packet: Path) -> None:
    """Patch only an offline clone, using a different disposable Linux preparer VM."""
    shutil.copy2(binary, target / "fault-agent")
    vm_id = None
    try:
        vm = helper.create_vm(
            {
                "runtime": "vz_linux",
                "template": str(boot),
                "workspace_path": str(target),
                "workspace_mount": "virtiofs",
                "network_policy": "deny_all",
                "timeout_sec": 90,
                "owner": "vz-failure-drill",
                "run_id": packet.name + "-offline-preparer",
            }
        )
        vm_id = vm.vm_id
        write_json(packet / "preparer.json", {"vm_id": vm_id, "boot": str(boot), "offline_target": str(target)})
        reply = helper.exec_guest(
            vm_id=vm_id,
            request={
                "argv": ["/bin/sh", "-eu", "-c", (FIXTURES / "install-agent.sh").read_text()],
                "cwd": "/workspace",
                "timeout_sec": 90,
            },
        )
        (packet / "install.stdout.log").write_bytes(reply.stdout)
        (packet / "install.stderr.log").write_bytes(reply.stderr)
        if reply.exit_code != 0 or digest(binary) != digest(target / "installed-agent"):
            raise RuntimeError(f"offline installation failed: {packet}")
    finally:
        if vm_id is not None and not helper.terminate_vm(vm_id):
            raise RuntimeError("preparer termination not confirmed")
        # A lost create reply is handled by the exclusive helper's outer cleanup.


def run_case(
    helper: Any, socket_path: Path, binary: Path, profile: str, negative: bool, healthy: Path, fault: Path, packet: Path
) -> dict[str, Any]:
    """Run an existing real drill; RED must prove actual dispatch, not a boot error."""
    filename, test_name, _, image_env, opt_in = TESTS[profile]
    env = dict(os.environ)
    for key in ("PYTEST_ADDOPTS", "PYTEST_PLUGINS", "TLDW_SANDBOX_VZ_LINUX_FAKE_EXEC"):
        env.pop(key, None)
    env.update(
        {
            "TEST_MODE": "0",
            "TLDW_SANDBOX_VZ_LINUX_E2E": "1",
            opt_in: "1",
            "TLDW_SANDBOX_VZ_LINUX_E2E_BASE_IMAGE": str(healthy),
            image_env: str(fault),
            "TLDW_SANDBOX_MACOS_HELPER_SOCKET": str(socket_path),
            "TLDW_SANDBOX_MACOS_HELPER_BINARY": str(binary),
            "PYTHONPATH": os.pathsep.join([str(REPO), str(FIXTURES)]),
        }
    )
    target = "tldw_Server_API/tests/sandbox/" + filename + "::" + test_name
    command = [
        sys.executable,
        "-m",
        "pytest",
        "-q",
        target,
        "--timeout=90",
        "--timeout-method=signal",
        "--basetemp=" + str(packet / "pytest"),
        "--junitxml=" + str(packet / "host.xml"),
    ]
    if negative:
        command.extend(["-p", "vz_" + profile + "_negative_control"])
    code = logged(command, packet / "host.log", env=env)
    result = test_result(packet / "host.xml", code, profile, negative)
    if negative:
        result["execution_proof"] = negative_execution(packet, profile)
        result["ok"] = result["ok"] and result["execution_proof"]["ok"]
    result["remaining_vm_ids"] = [vm.vm_id for vm in helper.list_vms().vms]
    result["disk_handles"] = disk_handles([healthy / "rootfs.img", fault / "rootfs.img"])
    result["ok"] = result["ok"] and result["remaining_vm_ids"] == [] and result["disk_handles"]["ok"]
    write_json(packet / "result.json", result)
    return result


def exercise(
    materializer: Any,
    ctl: Any,
    source: Path,
    binary: Path,
    evidence: Path,
    receipt: dict[str, Any],
    client_factory: Any,
) -> None:
    """Prepare both profiles and run positive/negative cases on independent clones."""
    disks: list[Path] = []
    agents = {}
    for profile in TESTS:
        packet = evidence / (profile + "-prepare")
        packet.mkdir(mode=0o700)
        agents[profile] = build_agent(profile, packet)
    with managed_helper(ctl, binary, evidence, receipt, disks, client_factory) as (helper, socket_path):
        for profile in TESTS:
            print(f"Preparing {profile} guest", flush=True)
            packet = evidence / (profile + "-prepare")
            fault = clone(materializer, source, evidence, profile + "-source", "healthy", disks)
            boot = clone(materializer, source, evidence, profile + "-preparer", "healthy", disks)
            install_agent(helper, boot, fault, agents[profile], packet)
            handles = disk_handles([boot / "rootfs.img", fault / "rootfs.img"])
            write_json(packet / "disk-handles.json", handles)
            if not handles["ok"]:
                raise RuntimeError("preparer still holds a disk")
            provenance = {
                "artifact_kind": "test_only_" + profile,
                "source_hashes": receipt["source_before"],
                "build": json.loads((packet / "build.json").read_text()),
                "rootfs_sha256": digest(fault / "rootfs.img"),
            }
            write_json(fault / "build-info.json", provenance)
            receipt.setdefault("fault_sources", {})[profile] = fingerprint(materializer, fault)
            for negative in (False, True):
                case = profile + ("-negative" if negative else "-positive")
                print(f"Running {case}", flush=True)
                packet = evidence / case
                packet.mkdir(mode=0o700)
                healthy_run = clone(materializer, source, evidence, case + "-healthy", "healthy", disks)
                fault_run = clone(materializer, fault, evidence, case + "-fault", profile, disks)
                result = run_case(helper, socket_path, binary, profile, negative, healthy_run, fault_run, packet)
                receipt.setdefault("cases", {})[case] = result
                write_json(evidence / "receipt.json", receipt)
                if not result["ok"]:
                    raise RuntimeError(f"{case} failed acceptance; see {packet}")


def main(argv: list[str] | None = None) -> int:
    """Require explicit consent and inputs; retain evidence regardless of outcome."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--allow-fault-injection", action="store_true", required=True)
    parser.add_argument("--source-bundle", type=Path, required=True)
    parser.add_argument("--helper", type=Path, required=True, help="Explicit, already signed helper executable")
    parser.add_argument(
        "--evidence-dir", type=Path, required=True, help="New directory under an existing durable parent"
    )
    args = parser.parse_args(argv)
    if sys.platform != "darwin" or platform.machine() != "arm64":
        parser.error("real VZ fault drills require an Apple Silicon macOS host")
    os.environ["TEST_MODE"] = "0"
    os.environ.pop("TLDW_SANDBOX_VZ_LINUX_FAKE_EXEC", None)
    materializer = load_module("failure_materializer", REPO / "tools/vz-linux-image/scripts/prepare-smoke-bundle.py")
    ctl = load_module("failure_helperctl", REPO / "tools/macos-vz-helper/scripts/vz-helperctl.py")
    from tldw_Server_API.app.core.Sandbox.macos_virtualization.helper_client import MacOSVirtualizationHelperClient

    source = args.source_bundle.expanduser().resolve(strict=True)
    binary = args.helper.expanduser().resolve(strict=True)
    materializer.validate_bundle(source)
    manifest = materializer.read_optional_json(source / "manifest.json")
    if manifest.get("rootfs", "rootfs.img") != "rootfs.img":
        parser.error("offline installer currently requires rootfs.img (an ext4 filesystem image)")
    evidence = create_evidence(args.evidence_dir, source)
    receipt: dict[str, Any] = {
        "schema_version": 1,
        "ok": False,
        "errors": [],
        "source": str(source),
        "helper": str(binary),
    }
    try:
        receipt["helper_sha256"] = digest(binary)
        input_files = [
            Path(__file__).resolve(),
            *FIXTURES.glob("*"),
            *[REPO / "tldw_Server_API/tests/sandbox" / item[0] for item in TESTS.values()],
            *list((REPO / "tools/tldw-agent").rglob("*.go")),
            REPO / "tools/tldw-agent/go.mod",
            REPO / "tools/tldw-agent/go.sum",
        ]
        receipt["input_sha256"] = {
            str(path.relative_to(REPO)): digest(path) for path in sorted(input_files) if path.is_file()
        }
        receipt["source_before"] = fingerprint(materializer, source)
        if logged(["/usr/bin/codesign", "--verify", "--strict", str(binary)], evidence / "codesign.log") != 0:
            raise RuntimeError("helper signature verification failed")
        exercise(
            materializer,
            ctl,
            source,
            binary,
            evidence,
            receipt,
            lambda path: MacOSVirtualizationHelperClient(socket_path=str(path), timeout_sec=180),
        )
    except (Exception, KeyboardInterrupt) as exc:  # noqa: BLE001 - CLI boundary retains traceback and fails
        receipt["errors"].append(f"{type(exc).__name__}: {exc}")
        (evidence / "error.log").write_text(traceback.format_exc(), encoding="utf-8")
    finally:
        verify_sources(materializer, source, evidence, receipt)
        receipt["ok"] = not receipt["errors"] and len(receipt.get("cases", {})) == 4
        write_json(evidence / "receipt.json", receipt)
    print(f"{'PASS' if receipt['ok'] else 'FAIL'}: {evidence / 'receipt.json'}")
    return 0 if receipt["ok"] else 1


if __name__ == "__main__":

    def interrupted(signum: int, frame: Any) -> None:
        """Let ordinary termination follow the same cleanup path as Ctrl-C."""
        raise KeyboardInterrupt(f"signal {signum}")

    signal.signal(signal.SIGTERM, interrupted)
    raise SystemExit(main())
