#!/usr/bin/env python3
"""Explicit, test-only real VZ fault preparation and acceptance workflow.

An opted-in run builds Go overlays, clones images into a new private evidence
directory, and starts an exclusively owned helper and disposable VMs. Source
bundles are read-only inputs. Logs, clones, and receipts remain for inspection;
normal failure/cancellation attempts VM/helper cleanup before final verification.
SIGKILL and host failure cannot execute Python cleanup and require operator review.
"""

from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
import os
import platform
import shutil
import signal

# Operator-selected local build/test tools; commands never use a shell.
import subprocess  # nosec B404
import sys
import tempfile
import threading
import traceback
from collections.abc import Iterator
from contextlib import contextmanager, suppress
from dataclasses import asdict
from pathlib import Path
from types import FrameType
from typing import Any

# Reports are generated by pytest in the private run, never downloaded.
from xml.etree import ElementTree as ET  # nosec B405

from loguru import logger

REPO = Path(__file__).resolve().parents[3]
FIXTURES = REPO / "tools/macos-vz-helper/Tests/failure_drill"
TESTS = {
    "mismatch": (
        "test_vz_linux_guest_mismatch_host_gated.py",
        "test_vz_linux_rejects_real_guest_missing_exec_then_runs_healthy_session",
        "Mismatched guest was not rejected",
        "TLDW_SANDBOX_VZ_LINUX_MISMATCH_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_GUEST_MISMATCH_DRILL",
    ),
    "readiness": (
        "test_vz_linux_readiness_host_gated.py",
        "test_vz_linux_readiness_timeout_then_healthy_session_reuse",
        "Readiness withholding did not fail",
        "TLDW_SANDBOX_VZ_LINUX_READINESS_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_READINESS_DRILL",
    ),
    "protocol": (
        "test_vz_linux_protocol_host_gated.py",
        "test_vz_linux_protocol_mismatch_then_healthy_session_reuse",
        "Protocol mismatch was not rejected",
        "TLDW_SANDBOX_VZ_LINUX_PROTOCOL_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_PROTOCOL_DRILL",
    ),
    "workspace": (
        "test_vz_linux_workspace_host_gated.py",
        "test_vz_linux_workspace_mismatch_then_healthy_session_reuse",
        "Workspace mismatch was not rejected",
        "TLDW_SANDBOX_VZ_LINUX_WORKSPACE_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_WORKSPACE_DRILL",
    ),
    "missing_agent": (
        "test_vz_linux_missing_agent_host_gated.py",
        "test_vz_linux_missing_agent_then_healthy_session_reuse",
        "Missing-agent startup did not fail",
        "TLDW_SANDBOX_VZ_LINUX_MISSING_AGENT_BASE_IMAGE",
        "TLDW_SANDBOX_VZ_LINUX_MISSING_AGENT_DRILL",
    ),
}


def load_module(name: str, path: Path) -> Any:
    """Reuse a trusted repository script, registering it in ``sys.modules``.

    Args:
        name: Unique import name; any existing entry is replaced.
        path: Local Python script to execute.
    Returns:
        The loaded module, exposing the original safety contracts.
    Raises:
        Exception: Import or script initialization fails.
    """
    spec = importlib.util.spec_from_file_location(name, path)
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


def digest(path: Path) -> str:
    """Hash an artifact without loading disk images into memory.

    Args:
        path: Existing readable artifact, opened read-only.
    Returns:
        Hexadecimal SHA-256 digest.
    Raises:
        OSError: The artifact cannot be read.
    """
    with path.open("rb") as handle:
        return hashlib.file_digest(handle, "sha256").hexdigest()


def write_json(path: Path, value: Any) -> None:
    """Write a readable receipt, replacing an existing file at ``path``.

    Args:
        path: File inside the caller-owned evidence directory.
        value: JSON-serializable receipt data.
    Raises:
        OSError: The file cannot be written.
        TypeError: The value cannot be serialized.
    """
    path.write_text(json.dumps(value, indent=2) + "\n", encoding="utf-8")


def create_evidence(path: Path, source: Path) -> Path:
    """Create an exclusive owner-only evidence directory.

    Args:
        path: New directory under an existing parent.
        source: Canonical bundle that must not contain evidence.
    Returns:
        Resolved path of the newly created directory.
    Raises:
        ValueError: Evidence would be inside the source, including via aliases.
        OSError: The directory exists or cannot be created.
    """
    path = path.expanduser().absolute()
    if path.resolve().is_relative_to(source.resolve()):
        raise ValueError("evidence must not be inside the source bundle")
    path.mkdir(mode=0o700)  # Parent must already exist; never overwrite an old run.
    return path.resolve()


def replace_once(source: str, anchor: str, replacement: str) -> str:
    """Apply one in-memory overlay without changing the production checkout.

    Args:
        source: Original guest source text.
        anchor: Text required to occur exactly once.
        replacement: Test-only replacement text.
    Returns:
        Modified source text.
    Raises:
        ValueError: Source drift made the anchor missing or ambiguous.
    """
    if source.count(anchor) != 1:
        raise ValueError("guest overlay anchor missing or ambiguous; review source drift")
    return source.replace(anchor, replacement, 1)


def test_result(path: Path, code: int, profile: str, negative: bool) -> dict[str, Any]:
    """Read JUnit evidence and distinguish intended RED from unrelated failure.

    Args:
        path: Local report produced in this private run.
        code: Pytest exit code.
        profile: A key in ``TESTS``.
        negative: Whether exactly the expected assertion must fail.
    Returns:
        Acceptance details; missing/malformed reports are unsuccessful results.
    """
    result: dict[str, Any] = {"ok": False, "exit_code": code}
    try:
        tree = ET.parse(path)  # nosec B314
    except (OSError, ET.ParseError) as exc:
        return {**result, "error": str(exc)}
    cases = list(tree.iter("testcase"))
    counts = {key: len(list(tree.iter(key))) for key in ("failure", "error", "skipped")}
    result.update(tests=len(cases), **counts)
    failures = list(tree.iter("failure"))
    if len(cases) != 1 or cases[0].get("name") != TESTS[profile][1]:
        return result
    result["ok"] = (
        code == int(negative)
        and counts == {"failure": int(negative), "error": 0, "skipped": 0}
        and (not negative or failures[0].get("message", "").startswith("Failed: " + TESTS[profile][2] + ":"))
    )
    return result


def cleanup_vms(helper: Any) -> dict[str, Any]:
    """Terminate every VM on an exclusively owned helper.

    Args:
        helper: This workflow's client, never a shared operator helper.
    Returns:
        Remaining VM IDs and all errors; unavailable enumeration fails closed.
    """
    errors = []
    remaining = None
    try:
        vms = helper.list_vms().vms
    except Exception as exc:  # noqa: BLE001 - accumulate failures; never abandon later cleanup
        errors.append(f"enumerate: {exc}")
    else:
        for vm in vms:
            try:
                if not helper.terminate_vm(vm.vm_id):
                    errors.append(f"terminate {vm.vm_id}: not confirmed")
            except Exception as exc:  # noqa: BLE001 - every cleanup error makes acceptance fail
                errors.append(f"terminate {vm.vm_id}: {exc}")
    try:
        remaining = [vm.vm_id for vm in helper.list_vms().vms]
    except Exception as exc:  # noqa: BLE001 - unavailable verification is a failed result
        errors.append(f"verify enumeration: {exc}")
    return {"ok": not errors and remaining == [], "errors": errors, "remaining_vm_ids": remaining}


def negative_execution(packet: Path, profile: str) -> dict[str, Any]:
    """Read proof of completed execution in the actual fault VM.

    Args:
        packet: Case evidence directory containing private pytest output.
        profile: A key in ``TESTS``.
    Returns:
        Validated execution proof, or an unsuccessful result on invalid evidence.
    """
    filename = {
        "mismatch": "guest-mismatch.json",
        "readiness": "guest-readiness.json",
        "protocol": "guest-protocol.json",
        "workspace": "guest-workspace.json",
        "missing_agent": "guest-missing-agent.json",
    }[profile]
    paths = [p for p in (packet / "pytest").glob("*/" + filename) if not p.parent.is_symlink() and not p.is_symlink()]
    if len(paths) != 1:
        return {"ok": False, "error": "expected exactly one guest receipt"}
    try:
        data = json.loads(paths[0].read_text(encoding="utf-8"))
        runs, created = data["runs"], data["created_vms"]
        if len(runs) != 1 or len(created) != 1:
            raise ValueError("expected one fault run and one fault VM")
        run, vm_id = runs[0], created[0]["vm_id"]
        ok = (
            isinstance(vm_id, str)
            and bool(vm_id)
            and run["phase"] == "completed"
            and run["exit_code"] == 0
            and run["stdout"] == profile + "-drill-first\n"
            and data["exec_vm_ids"] == [vm_id]
            and data["cleanup_errors"] == []
            and data["remaining_owned_vms"] == []
        )
        if profile == "readiness":
            proof = data["handshake_proof"]
            ok = ok and proof["vm_id"] == vm_id and proof["handshake_acknowledged"] is True
        elif profile == "protocol":
            proof = data["protocol_proof"]
            ok = ok and proof["vm_id"] == vm_id and proof["protocol_version"] == "1"
        elif profile == "workspace":
            guest = created[0]["guest_agent"]
            ok = (
                ok
                and isinstance(guest, dict)
                and guest.get("workspace_root") == "/workspace"
                and guest.get("capabilities_known") is True
                and isinstance(guest.get("capabilities"), list)
                and "exec" in guest["capabilities"]
                and "output_cap_v1" in guest["capabilities"]
            )
        elif profile == "missing_agent":
            proof = data["startup_proof"]
            ok = ok and proof["vm_id"] == vm_id and proof["mode"] == "start-original"
        return {"ok": ok, "receipt": str(paths[0]), "vm_id": vm_id, "run": run}
    except (OSError, ValueError, TypeError, KeyError) as exc:
        return {"ok": False, "error": str(exc)}


def disk_handles(disks: list[Path]) -> dict[str, Any]:
    """Probe open handles with lsof; an empty registry is insufficient evidence.

    Args:
        disks: Allocated disk paths to check, without modifying them.
    Returns:
        Success only for no allocated disks or a confirmed empty handle listing.
    Raises:
        OSError: lsof cannot start.
        subprocess.TimeoutExpired: The probe exceeds ten seconds.
    """
    if not disks:
        return {"ok": True, "reason": "no disks allocated"}
    result = subprocess.run(  # nosec B603
        ["/usr/sbin/lsof", "-Fpcn", "--", *map(str, disks)],
        capture_output=True,
        text=True,
        timeout=10,
        check=False,
    )
    return {
        "ok": result.returncode == 1 and not result.stdout and not result.stderr,
        "exit_code": result.returncode,
        "stdout": result.stdout,
        "stderr": result.stderr,
    }


@contextmanager
def managed_helper(
    ctl: Any, binary: Path, evidence: Path, receipt: dict[str, Any], disks: list[Path], client_factory: Any
) -> Iterator[tuple[Any, Path]]:
    """Own a fresh helper and attempt all cleanup stages on context exit.

    Args:
        ctl: Repository helper lifecycle module.
        binary: Explicit signed helper executable.
        evidence: Existing private directory retaining helper logs.
        receipt: Mutable result receiving lifecycle details and cleanup errors.
        disks: Mutable allocation list checked before stopping the helper.
        client_factory: Builds a helper client from its private socket path.
    Yields:
        Client and socket path of this exclusively owned helper.
    Raises:
        RuntimeError: Preflight/start fails; context-body exceptions propagate.
        OSError: Private runtime directory allocation fails.

    Cleanup errors are recorded rather than abandoning subsequent actions.
    The runtime directory is removed only after confirmed helper absence.
    """
    # mkdtemp creates an exclusive 0700 directory; /tmp keeps AF_UNIX paths short.
    runtime_name = tempfile.mkdtemp(prefix="tvz-fault.", dir="/tmp")  # nosec B108
    runtime = Path(runtime_name).resolve()
    socket_path, pid_file = runtime / "helper.sock", runtime / "helper.pid"
    lifecycle = receipt["lifecycle"] = {"runtime_dir": str(runtime), "socket_path": str(socket_path)}
    helper = None
    start_attempted = False
    try:
        preflight = ctl.collect_check_results(binary, socket_path, pid_file, evidence / "helper-logs")
        lifecycle["preflight"] = {name: asdict(result) for name, result in preflight}
        if not all(result.ok for _, result in preflight):
            raise RuntimeError("helper preflight failed; see lifecycle receipt")
        start_attempted = True
        lifecycle["start"] = asdict(ctl.start_helper(binary, socket_path, pid_file, evidence / "helper-logs"))
        if not lifecycle["start"]["ok"]:
            raise RuntimeError("managed helper start failed")
        helper = client_factory(socket_path)
        yield helper, socket_path
    finally:
        # Independently attempt cleanup, disk verification, stop, and absence proof.
        actions = []
        if helper is not None:
            actions.append(("vms", lambda: cleanup_vms(helper)))
        actions.append(("disk_handles_before_stop", lambda: disk_handles(disks)))
        if start_attempted:
            actions.append(("stop", lambda: asdict(ctl.stop_helper(binary, pid_file, socket_path=socket_path))))
        for name, action in actions:
            try:
                lifecycle[name] = action()
            except Exception as exc:  # noqa: BLE001 - persist each failure and still stop the helper
                lifecycle[name] = {"ok": False, "error": str(exc)}
            if not lifecycle[name]["ok"]:
                receipt["errors"].append(f"helper cleanup: {name}")
        try:
            absent = not ctl.socket_accepts_connection(socket_path) and not pid_file.exists()
            lifecycle["absent"] = absent
            if not absent:
                raise RuntimeError("helper absence not confirmed; retain runtime directory")
            runtime.rmdir()
            lifecycle["runtime_removed"] = True
        except Exception as exc:  # noqa: BLE001 - retain evidence and fail closed
            lifecycle["runtime_removed"] = False
            receipt["errors"].append(f"runtime cleanup: {exc}")


@contextmanager
def _defer_spawn_signals() -> Iterator[None]:
    """Defer handled termination signals until the new process has an owner.

    Do not block the OS signal mask: a child would inherit that mask and could
    then ignore TERM. Caught Python handlers reset on exec instead. The CLI
    calls this on the main thread; worker threads cannot receive Python signals.
    A burst during this short window is intentionally coalesced into its first
    signal, requesting one orderly cancellation rather than repeated unwinding.
    Once handlers are restored, subsequent signals retain their normal behavior.
    """
    if threading.current_thread() is not threading.main_thread():
        yield
        return
    handlers: dict[int, Any] = {}
    pending: list[int] = []

    def defer(signum: int, frame: FrameType | None) -> None:
        """Remember cancellation without interrupting process-handle registration."""
        pending.append(signum)

    try:
        for signum in (signal.SIGINT, signal.SIGTERM):
            handler = signal.getsignal(signum)
            if callable(handler):
                handlers[signum] = handler
                signal.signal(signum, defer)
        yield
    finally:
        for signum, handler in handlers.items():
            signal.signal(signum, handler)
        if pending:
            signal.raise_signal(pending[0])


def logged(
    command: list[str], log: Path, *, cwd: Path = REPO, env: dict[str, str] | None = None, timeout: int = 180
) -> int:
    """Run a bounded local command, retaining combined output in a log.

    Args:
        command: Trusted argv, executed without a shell.
        log: Caller-owned output file, replaced for this command.
        cwd: Command working directory.
        env: Complete child environment, or None to inherit.
        timeout: Maximum command runtime in seconds.
    Returns:
        Command exit code, including nonzero failures.
    Raises:
        OSError: Opening the log or spawning/signalling the child fails.
        subprocess.TimeoutExpired: Execution or bounded shutdown times out.
        BaseException: Cancellation propagates after process-tree termination
            and direct-child reaping (TERM grace of three seconds, then KILL).
    """
    with log.open("w", encoding="utf-8") as handle:
        process = None
        try:
            with _defer_spawn_signals():
                process = subprocess.Popen(  # nosec B603
                    command,
                    cwd=cwd,
                    env=env,
                    stdout=handle,
                    stderr=subprocess.STDOUT,
                    start_new_session=os.name == "posix",
                )
            return process.wait(timeout=timeout)
        except BaseException:
            if process is None:
                raise
            # Own a process group so compiler/test descendants cannot outlive cleanup.
            try:
                with suppress(ProcessLookupError):
                    if os.name == "posix":
                        os.killpg(process.pid, signal.SIGTERM)
                    else:
                        process.terminate()
                process.wait(timeout=3)
            except subprocess.TimeoutExpired:
                pass
            finally:
                # The leader may exit before a descendant that ignored SIGTERM.
                with suppress(ProcessLookupError):
                    if os.name == "posix":
                        os.killpg(process.pid, signal.SIGKILL)
                    else:
                        process.kill()
                process.wait(timeout=5)
            raise


def build_agent(profile: str, packet: Path) -> Path:
    """Build an offline Go overlay or stage the test-only startup launcher.

    Args:
        profile: A key in ``TESTS``.
        packet: Existing private directory for overlay, binary, log, and hashes.
    Returns:
        Path to the built test-only guest executable.
    Raises:
        ValueError: Source drift invalidates the overlay anchor.
        RuntimeError: Go build returns nonzero.
        OSError: An input or output artifact is unavailable.
        subprocess.TimeoutExpired: The build exceeds its bound.
    """
    if profile == "missing_agent":
        original_launcher = FIXTURES / "missing-agent-launcher.sh"
        binary = packet / "tldw-agent-guest"
        shutil.copy2(original_launcher, binary)
        binary.chmod(0o755)
        write_json(
            packet / "build.json",
            {
                "profile": profile,
                "fixture_sha256": digest(original_launcher),
                "agent_sha256": digest(binary),
                "artifact_kind": "test_only_guest_launcher",
            },
        )
        return binary
    original = REPO / "tools/tldw-agent/internal/guest/vsock_client.go"
    source = original.read_text(encoding="utf-8")
    if profile == "mismatch":
        source = replace_once(source, 'return []string{"exec", "output_cap_v1"}', 'return []string{"output_cap_v1"}')
    elif profile == "readiness":
        anchor = "\tif err := c.sendReady(conn, reader, server); err != nil {"
        source = replace_once(source, anchor, (FIXTURES / "withhold-ready.go.txt").read_text() + anchor)
    elif profile == "protocol":
        anchor = "\tif err := writeJSONLine(conn, HandshakeRequest{\n\t\tProtocolVersion: ProtocolVersion,"
        replacement = anchor.replace("ProtocolVersion: ProtocolVersion,", "ProtocolVersion: testProtocolVersion,")
        source = replace_once(source, anchor, (FIXTURES / "protocol-mismatch.go.txt").read_text() + replacement)
    elif profile == "workspace":
        anchor = "\tif err := writeJSONLine(conn, HandshakeRequest{"
        source = replace_once(source, anchor, (FIXTURES / "workspace-mismatch.go.txt").read_text() + anchor)
        source = replace_once(source, "WorkspaceRoot:   c.cfg.WorkspaceRoot,", "WorkspaceRoot:   testWorkspaceRoot,")
    else:
        raise ValueError(f"unknown guest fault profile: {profile}")
    overlay_source = packet / "vsock_client.go"
    overlay_source.write_text(source, encoding="utf-8")
    overlay = packet / "overlay.json"
    write_json(overlay, {"Replace": {str(original): str(overlay_source)}})
    binary = packet / "tldw-agent-guest"
    env = {
        **os.environ,
        "GOOS": "linux",
        "GOARCH": "arm64",
        "CGO_ENABLED": "0",
        "GOPROXY": "off",
        "GOSUMDB": "off",
        "GOTOOLCHAIN": "local",
    }
    command = ["go", "build", "-overlay=" + str(overlay), "-o", str(binary), "./cmd/tldw-agent-guest"]
    if logged(command, packet / "build.log", cwd=REPO / "tools/tldw-agent", env=env) != 0:
        raise RuntimeError(f"{profile} guest build failed; see {packet / 'build.log'}")
    write_json(
        packet / "build.json",
        {
            "profile": profile,
            "command": command,
            "production_source_sha256": digest(original),
            "overlay_sha256": digest(overlay_source),
            "agent_sha256": digest(binary),
        },
    )
    return binary


def fingerprint(materializer: Any, bundle: Path) -> dict[str, str]:
    """Read hashes of boot artifacts and available manifest/build provenance.

    Args:
        materializer: Repository image materialization module.
        bundle: Valid bundle directory, never modified here.
    Returns:
        Artifact-name to SHA-256 mapping.
    Raises:
        OSError: An artifact cannot be read.
        ValueError: Bundle metadata is invalid.
    """
    names = materializer.bundle_artifact_names(bundle)
    names += [name for name in ("manifest.json", "build-info.json") if (bundle / name).is_file()]
    return {name: digest(bundle / name) for name in names}


def verify_sources(materializer: Any, source: Path, evidence: Path, receipt: dict[str, Any]) -> None:
    """Verify every source independently, even after failed drills.

    Args:
        materializer: Repository image materialization module.
        source: Canonical read-only input bundle.
        evidence: Run directory containing prepared fault-source clones.
        receipt: Mutable result with initial hashes; receives final hashes,
            per-source outcomes, and every verification error.
    """
    sources = [("canonical", source, receipt.get("source_before"))]
    sources.extend(
        (profile, evidence / "image-store/runs" / (profile + "-source/bundle"), hashes)
        for profile, hashes in receipt.get("fault_sources", {}).items()
    )
    for label, bundle, before in sources:
        unchanged = False
        try:
            after = fingerprint(materializer, bundle)
            unchanged = after == before
            if label == "canonical":
                receipt["source_after"] = after
            if not unchanged:
                raise RuntimeError("source changed")
        except Exception as exc:  # noqa: BLE001 - independently verify every source on failure
            receipt["errors"].append(f"{label} source verification: {exc}")
        if label != "canonical":
            receipt.setdefault("fault_sources_unchanged", {})[label] = unchanged


def clone(materializer: Any, source: Path, evidence: Path, run_id: str, template: str, disks: list[Path]) -> Path:
    """Allocate a disposable bundle via the normal smoke image-store abstraction.

    Args:
        materializer: Repository image materialization module.
        source: Bundle to clone, never modified by this operation.
        evidence: Run directory owning the image store.
        run_id: Unique clone identifier within that store.
        template: Template name to register or reuse.
        disks: Allocation list to append for later handle verification.
    Returns:
        Disposable bundle path; its files remain in evidence after cleanup.
    Raises:
        Exception: Image validation, registration, or clone allocation fails.
    """
    bundle = materializer.prepare_bundle(
        materializer.parse_args(
            [
                "--source-bundle",
                str(source),
                "--store-root",
                str(evidence / "image-store"),
                "--run-id",
                run_id,
                "--template-name",
                template,
            ]
        )
    )
    disks.append(bundle / "rootfs.img")
    return bundle


def install_agent(
    helper: Any, boot: Path, target: Path, binary: Path, packet: Path, *, installer: Path | None = None
) -> None:
    """Install a fault agent into an offline clone using a disposable preparer VM.

    Args:
        helper: Client for this workflow's exclusively owned helper.
        boot: Disposable healthy boot bundle, distinct from target.
        target: Offline disposable bundle exported writable to the preparer.
        binary: Test-only guest executable to install.
        packet: Existing private directory retaining preparer and exec evidence.
        installer: Test-only offline installer, or the normal fault installer.
    Raises:
        RuntimeError: Installation verification or termination fails.
        Exception: Helper RPC or artifact I/O fails.

    Always attempts termination of a known preparer VM; outer helper cleanup
    covers lost create replies. Never pass the canonical bundle as target.
    A simultaneous cleanup failure is attached as a note to the primary error
    so the retained traceback records both without replacing the original cause.
    """
    shutil.copy2(binary, target / "fault-agent")
    vm_id = None
    primary_error: BaseException | None = None
    try:
        vm = helper.create_vm(
            {
                "runtime": "vz_linux",
                "template": str(boot),
                "workspace_path": str(target),
                "workspace_mount": "virtiofs",
                "network_policy": "deny_all",
                "timeout_sec": 90,
                "owner": "vz-failure-drill",
                "run_id": packet.name + "-offline-preparer",
            }
        )
        vm_id = vm.vm_id
        write_json(packet / "preparer.json", {"vm_id": vm_id, "boot": str(boot), "offline_target": str(target)})
        reply = helper.exec_guest(
            vm_id=vm_id,
            request={
                "argv": ["/bin/sh", "-eu", "-c", (installer or FIXTURES / "install-agent.sh").read_text()],
                "cwd": "/workspace",
                "timeout_sec": 90,
            },
        )
        (packet / "install.stdout.log").write_bytes(reply.stdout)
        (packet / "install.stderr.log").write_bytes(reply.stderr)
        if reply.exit_code != 0 or digest(binary) != digest(target / "installed-agent"):
            raise RuntimeError(f"offline installation failed: {packet}")
    except BaseException as exc:
        primary_error = exc
        raise
    finally:
        try:
            if vm_id is not None and not helper.terminate_vm(vm_id):
                raise RuntimeError("preparer termination not confirmed")
        except Exception as cleanup_error:  # noqa: BLE001 - retain both failures at the CLI boundary
            if primary_error is None:
                raise
            primary_error.add_note(f"preparer cleanup failed: {type(cleanup_error).__name__}: {cleanup_error}")
        # A lost create reply is handled by the exclusive helper's outer cleanup.


def run_case(
    helper: Any, socket_path: Path, binary: Path, profile: str, negative: bool, healthy: Path, fault: Path, packet: Path
) -> dict[str, Any]:
    """Run an existing real drill; intended RED must prove actual guest execution.

    Args:
        helper: Exclusive helper used to verify empty inventory afterward.
        socket_path: That helper's socket, never an operator-shared socket.
        binary: Signed helper executable passed to the drill.
        profile: A key in ``TESTS``.
        negative: Enable only the selected test-only negative-control plugin.
        healthy: Fresh healthy disposable bundle.
        fault: Fresh fault disposable bundle.
        packet: Private directory retaining logs, JUnit, and acceptance result.
    Returns:
        Result including acceptance, VM inventory, and disk-handle evidence.
    Raises:
        Exception: Process/RPC/I/O failures propagate to outer helper cleanup.
    """
    filename, test_name, _, image_env, opt_in = TESTS[profile]
    env = dict(os.environ)
    for key in ("PYTEST_ADDOPTS", "PYTEST_PLUGINS", "TLDW_SANDBOX_VZ_LINUX_FAKE_EXEC"):
        env.pop(key, None)
    env.update(
        {
            "TEST_MODE": "0",
            "TLDW_SANDBOX_VZ_LINUX_E2E": "1",
            opt_in: "1",
            "TLDW_SANDBOX_VZ_LINUX_E2E_BASE_IMAGE": str(healthy),
            image_env: str(fault),
            "TLDW_SANDBOX_MACOS_HELPER_SOCKET": str(socket_path),
            "TLDW_SANDBOX_MACOS_HELPER_BINARY": str(binary),
            "PYTHONPATH": os.pathsep.join([str(REPO), str(FIXTURES)]),
        }
    )
    target = "tldw_Server_API/tests/sandbox/" + filename + "::" + test_name
    command = [
        sys.executable,
        "-m",
        "pytest",
        "-q",
        target,
        "--timeout=90",
        "--timeout-method=signal",
        "--basetemp=" + str(packet / "pytest"),
        "--junitxml=" + str(packet / "host.xml"),
    ]
    if negative:
        command.extend(["-p", "vz_" + profile + "_negative_control"])
    code = logged(command, packet / "host.log", env=env)
    result = test_result(packet / "host.xml", code, profile, negative)
    if negative:
        result["execution_proof"] = negative_execution(packet, profile)
        result["ok"] = result["ok"] and result["execution_proof"]["ok"]
    result["remaining_vm_ids"] = [vm.vm_id for vm in helper.list_vms().vms]
    result["disk_handles"] = disk_handles([healthy / "rootfs.img", fault / "rootfs.img"])
    result["ok"] = result["ok"] and result["remaining_vm_ids"] == [] and result["disk_handles"]["ok"]
    write_json(packet / "result.json", result)
    return result


def exercise(
    materializer: Any,
    ctl: Any,
    source: Path,
    binary: Path,
    evidence: Path,
    receipt: dict[str, Any],
    client_factory: Any,
) -> None:
    """Prepare all profiles and run positive/negative cases on independent clones.

    Args:
        materializer: Repository image materialization module.
        ctl: Repository helper lifecycle module.
        source: Canonical bundle, read-only throughout.
        binary: Signed helper executable.
        evidence: New private directory retaining all clones and case artifacts.
        receipt: Mutable result with source hashes; receives case/source results.
        client_factory: Creates a client for the exclusively owned helper.
    Raises:
        Exception: Preparation, execution, or acceptance fails. Helper cleanup
            runs on context exit; the caller must still verify source hashes.
    """
    disks: list[Path] = []
    agents = {}
    for profile in TESTS:
        packet = evidence / (profile + "-prepare")
        packet.mkdir(mode=0o700)
        agents[profile] = build_agent(profile, packet)
    with managed_helper(ctl, binary, evidence, receipt, disks, client_factory) as (helper, socket_path):
        for profile in TESTS:
            logger.bind(profile=profile).info("Preparing fault guest")
            packet = evidence / (profile + "-prepare")
            fault = clone(materializer, source, evidence, profile + "-source", "healthy", disks)
            boot = clone(materializer, source, evidence, profile + "-preparer", "healthy", disks)
            installer = FIXTURES / "install-missing-agent.sh" if profile == "missing_agent" else None
            install_agent(helper, boot, fault, agents[profile], packet, installer=installer)
            handles = disk_handles([boot / "rootfs.img", fault / "rootfs.img"])
            write_json(packet / "disk-handles.json", handles)
            if not handles["ok"]:
                raise RuntimeError("preparer still holds a disk")
            provenance = {
                "artifact_kind": "test_only_" + profile,
                "source_hashes": receipt["source_before"],
                "build": json.loads((packet / "build.json").read_text()),
                "rootfs_sha256": digest(fault / "rootfs.img"),
            }
            write_json(fault / "build-info.json", provenance)
            receipt.setdefault("fault_sources", {})[profile] = fingerprint(materializer, fault)
            for negative in (False, True):
                case = profile + ("-negative" if negative else "-positive")
                logger.bind(profile=profile, case=case).info("Running guest failure drill")
                packet = evidence / case
                packet.mkdir(mode=0o700)
                healthy_run = clone(materializer, source, evidence, case + "-healthy", "healthy", disks)
                fault_run = clone(materializer, fault, evidence, case + "-fault", profile, disks)
                result = run_case(helper, socket_path, binary, profile, negative, healthy_run, fault_run, packet)
                receipt.setdefault("cases", {})[case] = result
                write_json(evidence / "receipt.json", receipt)
                if not result["ok"]:
                    raise RuntimeError(f"{case} failed acceptance; see {packet}")


def main(argv: list[str] | None = None) -> int:
    """Run explicitly opted-in Apple Silicon fault drills and retain evidence.

    Args:
        argv: CLI arguments, or None for the process command line.
    Returns:
        Zero only when all cases and cleanup/source verification pass;
        one for failures after evidence allocation, including cancellation.
    Raises:
        SystemExit: Missing consent/arguments or unsupported host/input shape.
        Exception: Initial input validation or evidence allocation fails.

    Clears fake-exec and test-mode settings in the current environment. After
    evidence allocation, caught failures receive a traceback and final receipt.
    """
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--allow-fault-injection", action="store_true", required=True)
    parser.add_argument("--source-bundle", type=Path, required=True)
    parser.add_argument("--helper", type=Path, required=True, help="Explicit, already signed helper executable")
    parser.add_argument(
        "--evidence-dir", type=Path, required=True, help="New directory under an existing durable parent"
    )
    args = parser.parse_args(argv)
    if sys.platform != "darwin" or platform.machine() != "arm64":
        parser.error("real VZ fault drills require an Apple Silicon macOS host")
    os.environ["TEST_MODE"] = "0"
    os.environ.pop("TLDW_SANDBOX_VZ_LINUX_FAKE_EXEC", None)
    materializer = load_module("failure_materializer", REPO / "tools/vz-linux-image/scripts/prepare-smoke-bundle.py")
    ctl = load_module("failure_helperctl", REPO / "tools/macos-vz-helper/scripts/vz-helperctl.py")
    from tldw_Server_API.app.core.Sandbox.macos_virtualization.helper_client import MacOSVirtualizationHelperClient

    source = args.source_bundle.expanduser().resolve(strict=True)
    binary = args.helper.expanduser().resolve(strict=True)
    materializer.validate_bundle(source)
    manifest = materializer.read_optional_json(source / "manifest.json")
    if manifest.get("rootfs", "rootfs.img") != "rootfs.img":
        parser.error("offline installer currently requires rootfs.img (an ext4 filesystem image)")
    evidence = create_evidence(args.evidence_dir, source)
    receipt: dict[str, Any] = {
        "schema_version": 1,
        "ok": False,
        "errors": [],
        "source": str(source),
        "helper": str(binary),
    }
    try:
        receipt["helper_sha256"] = digest(binary)
        input_files = [
            Path(__file__).resolve(),
            REPO / "tools/vz-linux-image/scripts/prepare-smoke-bundle.py",
            REPO / "tools/macos-vz-helper/scripts/vz-helperctl.py",
            *FIXTURES.glob("*"),
            *[REPO / "tldw_Server_API/tests/sandbox" / item[0] for item in TESTS.values()],
            *list((REPO / "tools/tldw-agent").rglob("*.go")),
            REPO / "tools/tldw-agent/go.mod",
            REPO / "tools/tldw-agent/go.sum",
        ]
        receipt["input_sha256"] = {
            str(path.relative_to(REPO)): digest(path) for path in sorted(input_files) if path.is_file()
        }
        receipt["source_before"] = fingerprint(materializer, source)
        if logged(["/usr/bin/codesign", "--verify", "--strict", str(binary)], evidence / "codesign.log") != 0:
            raise RuntimeError("helper signature verification failed")
        exercise(
            materializer,
            ctl,
            source,
            binary,
            evidence,
            receipt,
            lambda path: MacOSVirtualizationHelperClient(socket_path=str(path), timeout_sec=180),
        )
    except (Exception, KeyboardInterrupt) as exc:  # noqa: BLE001 - CLI boundary retains traceback and fails
        receipt["errors"].append(f"{type(exc).__name__}: {exc}")
        (evidence / "error.log").write_text(traceback.format_exc(), encoding="utf-8")
    finally:
        verify_sources(materializer, source, evidence, receipt)
        expected_cases = {profile + suffix for profile in TESTS for suffix in ("-positive", "-negative")}
        cases = receipt.get("cases", {})
        receipt["ok"] = (
            not receipt["errors"] and set(cases) == expected_cases and all(case["ok"] for case in cases.values())
        )
        write_json(evidence / "receipt.json", receipt)
    print(f"{'PASS' if receipt['ok'] else 'FAIL'}: {evidence / 'receipt.json'}")
    return 0 if receipt["ok"] else 1


if __name__ == "__main__":

    def interrupted(signum: int, frame: Any) -> None:
        """Let ordinary termination follow the same cleanup path as Ctrl-C."""
        raise KeyboardInterrupt(f"signal {signum}")

    signal.signal(signal.SIGTERM, interrupted)
    raise SystemExit(main())
