"""Dependency-free public limits for the ``notes.link`` Sync contract."""

NOTES_LINK_WEIGHT_MAX = 1_000_000.0
NOTES_LINK_LABEL_MAX_CHARS = 256
NOTES_LINK_PROPERTIES_MAX_KEYS = 64
NOTES_LINK_PROPERTIES_MAX_DEPTH = 4
NOTES_LINK_PROPERTIES_MAX_BYTES = 16 * 1024
NOTES_LINK_REASON_MAX_CHARS = 256

__all__ = [
    "NOTES_LINK_LABEL_MAX_CHARS",
    "NOTES_LINK_PROPERTIES_MAX_BYTES",
    "NOTES_LINK_PROPERTIES_MAX_DEPTH",
    "NOTES_LINK_PROPERTIES_MAX_KEYS",
    "NOTES_LINK_REASON_MAX_CHARS",
    "NOTES_LINK_WEIGHT_MAX",
]
