export { DocumentInfoTab } from "./DocumentInfoTab"
export { TableOfContentsTab } from "./TableOfContentsTab"
export { QuickInsightsTab } from "./QuickInsightsTab"
export { ReferencesTab } from "./ReferencesTab"
export { PagesTab } from "./PagesTab"
