"""Public model and error contracts for MCP LSP tooling."""

from .backends import (
    LSP_CODE_ACTIONS_TOOL,
    LSP_DEFINITION_TOOL,
    LSP_DIAGNOSTICS_TOOL,
    LSP_DOCUMENT_SYMBOLS_TOOL,
    LSP_FORMAT_PREVIEW_TOOL,
    LSP_HOVER_TOOL,
    LSP_OPERATION_TOOLS,
    LSP_REFERENCES_TOOL,
    LSP_SIGNATURE_HELP_TOOL,
    LSP_STATUS_TOOL,
    LSP_TOOL_NAMES,
    LSP_WORKSPACE_SYMBOLS_TOOL,
    CodeActionsRequest,
    DiagnosticsRequest,
    DocumentSymbolsRequest,
    FakeLspBackend,
    FormatPreviewRequest,
    LspBackend,
    PositionRequest,
    ReferencesRequest,
    WorkspaceSymbolsRequest,
)
from .config import DEFAULT_LSP_CONFIG, LspRuntimeConfig
from .errors import LSP_REASON_CODES, LspToolError, redact_lsp_detail
from .executables import LspExecutableResolver, ResolvedLspExecutable
from .filtering import PathAllowPredicate, filter_lsp_result_paths
from .jsonrpc import LspJsonRpcClient
from .models import (
    LspBackendStatus,
    LspCodeAction,
    LspCodeActionsResult,
    LspDiagnostic,
    LspDiagnosticsResult,
    LspHover,
    LspLocation,
    LspLocationsResult,
    LspPosition,
    LspPreview,
    LspRange,
    LspSignatureHelp,
    LspSymbol,
    LspSymbolsResult,
    LspTextEdit,
)
from .pylsp import PylspLspBackend
from .router import LspCapabilityRouter
from .ruff import RuffLspBackend
from .service import LspCodeIntelligenceService
from .sessions import LspManagedSession, LspSessionManager

__all__ = [
    "CodeActionsRequest",
    "DEFAULT_LSP_CONFIG",
    "DiagnosticsRequest",
    "DocumentSymbolsRequest",
    "FakeLspBackend",
    "FormatPreviewRequest",
    "LSP_CODE_ACTIONS_TOOL",
    "LSP_DEFINITION_TOOL",
    "LSP_DIAGNOSTICS_TOOL",
    "LSP_DOCUMENT_SYMBOLS_TOOL",
    "LSP_FORMAT_PREVIEW_TOOL",
    "LSP_HOVER_TOOL",
    "LSP_OPERATION_TOOLS",
    "LSP_REASON_CODES",
    "LSP_REFERENCES_TOOL",
    "LSP_SIGNATURE_HELP_TOOL",
    "LSP_STATUS_TOOL",
    "LSP_TOOL_NAMES",
    "LSP_WORKSPACE_SYMBOLS_TOOL",
    "LspBackend",
    "LspBackendStatus",
    "LspCapabilityRouter",
    "LspCodeAction",
    "LspCodeActionsResult",
    "LspCodeIntelligenceService",
    "LspExecutableResolver",
    "LspJsonRpcClient",
    "LspManagedSession",
    "LspDiagnostic",
    "LspDiagnosticsResult",
    "LspHover",
    "LspLocation",
    "LspLocationsResult",
    "LspPosition",
    "LspPreview",
    "LspRange",
    "LspRuntimeConfig",
    "LspSessionManager",
    "LspSignatureHelp",
    "LspSymbol",
    "LspSymbolsResult",
    "LspTextEdit",
    "LspToolError",
    "PathAllowPredicate",
    "PositionRequest",
    "PylspLspBackend",
    "ReferencesRequest",
    "ResolvedLspExecutable",
    "RuffLspBackend",
    "WorkspaceSymbolsRequest",
    "filter_lsp_result_paths",
    "redact_lsp_detail",
]
