"""Public PR 1 contracts for canonical admin outgoing webhooks."""

from .catalog import (
    EVENT_API_VERSION,
    EVENT_CATALOG,
    WebhookCatalogItem,
    normalize_subscriptions,
    validate_subscriptions,
)
from .config import (
    AdminWebhookMode,
    AdminWebhookSettings,
    WebhookRouteSelection,
)
from .domain import (
    IdempotencyClaim,
    IdempotencyClaimState,
    IdempotencyScope,
    WebhookError,
    WebhookErrorCode,
    WebhookLimits,
    WebhookMigrationSummary,
    WebhookRegistration,
    WebhookStatus,
    build_idempotency_scope,
    build_registration_etag,
    canonical_request_hash,
    idempotency_lookup_digest,
    normalize_request_id,
    parse_registration_etag,
    redact_target,
    validate_idempotency_key,
    validate_webhook_target,
)

__all__ = [
    "AdminWebhookMode",
    "AdminWebhookSettings",
    "EVENT_API_VERSION",
    "EVENT_CATALOG",
    "IdempotencyClaim",
    "IdempotencyClaimState",
    "IdempotencyScope",
    "WebhookCatalogItem",
    "WebhookError",
    "WebhookErrorCode",
    "WebhookLimits",
    "WebhookMigrationSummary",
    "WebhookRegistration",
    "WebhookRouteSelection",
    "WebhookStatus",
    "build_idempotency_scope",
    "build_registration_etag",
    "canonical_request_hash",
    "idempotency_lookup_digest",
    "normalize_request_id",
    "normalize_subscriptions",
    "parse_registration_etag",
    "redact_target",
    "validate_idempotency_key",
    "validate_subscriptions",
    "validate_webhook_target",
]
